In [1]:
%pip install numpy

Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (2.4.2)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install lingua-language-detector

Requirement already satisfied: lingua-language-detector in /opt/homebrew/lib/python3.11/site-packages (2.1.1)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
from lingua import Language, LanguageDetectorBuilder

In [4]:
posts = pd.read_json('r_newyork_posts.jsonl', lines=True)
posts

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,view_count,visited,wls,crosspost_parent,crosspost_parent_list,poll_data,gallery_data,is_gallery,media_metadata,author_cakeday
0,{'retrieved_2nd_on': 1730549029},[],False,NaN,NaN,False,Life_Worker_5936,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'is_edited': True, 'retrieved_2nd_on': 173055...",[],False,NaN,NaN,False,goatfuckersupreme,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'retrieved_2nd_on': 1730555349},[],False,NaN,NaN,False,saltystark,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'retrieved_2nd_on': 1730560122},[],False,NaN,NaN,False,Icy_Mammoth_9799,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'retrieved_2nd_on': 1730599759},[],False,NaN,NaN,False,Rinoremover1,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8401,{'retrieved_2nd_on': 1762135792},[],False,NaN,NaN,False,news-10,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8402,{'retrieved_2nd_on': 1762136110},[],False,NaN,NaN,False,Embarrassed-Joke9576,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8403,{'retrieved_2nd_on': 1762136349},[],False,NaN,NaN,False,criimsonshade,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8404,{'retrieved_2nd_on': 1762142567},[],False,NaN,NaN,False,dancehallchef,NaN,NaN,[],...,NaN,False,6,t3_1ol761t,"[{'all_awardings': [], 'allow_live_comments': ...",NaN,NaN,NaN,NaN,NaN
8405,{'retrieved_2nd_on': 1762143291},[],False,NaN,NaN,False,ChrisMiles19911,NaN,NaN,[],...,NaN,False,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
posts["title"]

0                          Benny The Butcher Is A Scammer
1       Receiving biweekly checks from State Departmen...
2        Ballot not counted (not eligible to cast ballot)
3               Dinner recommendations for large groups?
4       Instagram-famous squirrel named Peanut seized ...
                              ...
8401    50th Anniversary State of the Park Report high...
8402                        where to look for a male fwb?
8403    EMERGENCY!! SOLD OUT Times Square NYE Hotel St...
8404    A Privacy Coordination Layer For Contactless E...
8405    Hudson Valley recipes, cuisine, ingredients!! ...
Name: title, Length: 8406, dtype: str

In [6]:
comments = pd.read_json('r_newyork_comments.jsonl', lines=True)
comments

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,subreddit_name_prefixed,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,ups,user_reports,editable,author_cakeday
0,"{'is_edited': True, 'retrieved_2nd_on': 173055...",[],NaN,NaN,False,NaN,no-gail-71,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,-1,[],NaN,NaN
1,{'retrieved_2nd_on': 1730551743},[],NaN,NaN,False,NaN,Coxy_16,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
2,"{'is_edited': True, 'retrieved_2nd_on': 173055...",[],NaN,NaN,False,NaN,TieMelodic1173,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,5,[],NaN,NaN
3,{'retrieved_2nd_on': 1730553082},[],NaN,NaN,False,NaN,euclidiancandlenut,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,3,[],NaN,NaN
4,{'retrieved_2nd_on': 1730553352},[],NaN,NaN,False,NaN,Sufficient-West4149,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,-2,[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131671,{'retrieved_2nd_on': 1762145251},[],NaN,NaN,False,NaN,AbstractTeserract,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,3,[],NaN,NaN
131672,{'retrieved_2nd_on': 1762145738},[],NaN,NaN,False,NaN,CardOk755,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
131673,{'retrieved_2nd_on': 1762145810},[],NaN,NaN,False,NaN,motorboatingthoseCs,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
131674,{'retrieved_2nd_on': 1762146004},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
131675,{'retrieved_2nd_on': 1762146421},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN

In [7]:
posts.iloc[:1]['name']

0    t3_1ggssct
Name: name, dtype: str

In [8]:
comments.iloc[:1]['link_id']

0    t3_1ggjpu5
Name: link_id, dtype: str

In [9]:
# for the first 10 posts, find all comments
first_10_posts = posts.iloc[:10]['name']
first_10_comments = comments[comments['link_id'].isin(first_10_posts)]
first_10_comments

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,subreddit_name_prefixed,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,ups,user_reports,editable,author_cakeday
76,{'retrieved_2nd_on': 1730610418},[],NaN,NaN,False,NaN,citytiger,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,17,[],NaN,NaN
77,{'retrieved_2nd_on': 1730610675},[],NaN,NaN,False,NaN,Rinoremover1,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,11,[],NaN,NaN
78,"{'is_edited': True, 'retrieved_2nd_on': 173061...",[],NaN,NaN,False,NaN,citytiger,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,19,[],NaN,NaN
79,{'retrieved_2nd_on': 1730610951},[],NaN,NaN,False,NaN,LordJesterTheFree,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,7,[],NaN,NaN
80,"{'is_edited': True, 'retrieved_2nd_on': 173061...",[],NaN,NaN,False,NaN,citytiger,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2688,{'retrieved_2nd_on': 1730925885},[],NaN,NaN,False,NaN,songyie84,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,2,[],NaN,NaN
2704,{'retrieved_2nd_on': 1730943949},[],NaN,NaN,False,NaN,GrkLifter,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,2,[],NaN,NaN
2731,{'retrieved_2nd_on': 1730961307},[],NaN,NaN,False,NaN,Perfect-Frosting9602,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
2895,{'retrieved_2nd_on': 1731047200},[],NaN,NaN,False,NaN,NonstopNightmare,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
70385,{'retrieved_2nd_on': 1745940885},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN

In [10]:
# print post name and their comments
for i in range (10):
    post_name = posts.iloc[i]['name']
    post_title = posts.iloc[i]['title']
    post_comments = comments[comments['link_id'] == post_name]
    print(f"Post: {post_title}")
    print("Comments:")
    comment_list = []
    for comment in post_comments['body']:
        comment_list.append(comment)
    print(comment_list)
    print("\n")

Post: Benny The Butcher Is A Scammer
Comments:
[]


Post: Receiving biweekly checks from State Department of Taxation & Finance?
Comments:
[]


Post: Ballot not counted (not eligible to cast ballot)
Comments:
[]


Post: Dinner recommendations for large groups?
Comments:
[]


Post: Instagram-famous squirrel named Peanut seized by New York state authorities
Comments:
['totally unacceptable. Shame on the anonymous miserable Karen and the DEC.', "I agree.  According to the article, the squirrel was a rescue that was incapable of surviving on it's own.", 'contact state DEC and tell them they where wrong to do this and they should be ashamed of themselves. Please be polite in your messages.', "Who do I call? The fact that they're not saying whether they euthanized peanut or not is really concerning", 'Not entirely sure. Your state legislator could give you the number.', 'Great this is what my tax dollars are used on\n\nThanks again.', 'And euthanized so they could test it for rabies.\xa0', 'I understand this was a “famous” squirrel, but can’t we put this in perspective. I mean many, many squirrels are legally hunted every year in NY.', 'Ohhhhhh they’re getting torn apart in the comments of they’re latest post. Fuck them.', 'They apparently euthanized the animal to check for rabies…', 'What made it incapable? \xa0I took care of a lady once who took care of squirrels a couple times in her life. \xa0She showed me photo albums of the squirrel dressed in various cute little outfits. \xa0So what would happen is a nest or tree with nest would get knocked down the a storm. \xa0They would save the babies and raise them. \xa0Once they because adults she said you would just release them or they become a nuisance. \xa0Didn’t matter if they were raised in captivity they would thrive in the outdoors on their own', 'They deserve it', 'They didn’t give a FUCK that I called and asked about hammerhead flatworms that I found on my property 15 miles from the Avon office but no we gotta over reach/pet murder/and pretend they do shit by the book. I knew someone that worked up north as a biologist the amount of shit they hide and lie about cuz they don’t wana do they’re Fuckn jobs is nuts. Unless they can get fines of course.', "And this is why you don't keep wildlife as pets.", 'He released the squirrel. The next day, it showed up on his doorstep with a stubby bone left where the squirrel’s tail should’ve been.', 'He saved the squirrel when he was baby, raised him till he could survive, and tried to release him. Peanut came back the next day injured.', 'All illegal.  He could have tried calling a legal wildlife rehab and done it the right way.  Nope, he wanted a pet.  This is what happens.', "Who the hell are the clique of 'legal rehabbers' and their bootlicking friends to tell people where 'wild' (not really) animals belong? If you think that a few squirrels here and there getting to live the high life with humans is some grave crime against nature, I have a bridge to sell you.\n\nI can't express how sick and tired I am of people like you drinking the cool-aide about how animals 'deserve to be wild'.", 'Lol.  So then you would be ok if someone wanted to keep tigers or wolves as pets innurban areas, right?  What if I wanted to keep squirrels but so I could kill them for food once large enough?\n\nWhat "clique"?  They are *begging* people to become certified wildlife rehabbers.  It just takes time and training.  This guy decided to not follow the rules and Peanut paid the price.', "My point is that the 'rules' are ridiculous. Yeah, I believe squirrels should be able to be kept as pets. Do you throw this argument about wolves and tigers at people who own cats or dogs? Or, for an example that hasn't been 'truly' domesticated, people who own gerbils? \n\nNo one in the US has EVER gotten rabies from a tree squirrel. It's literally never happened. This incident has nothing to do with public safety. It's an expression of the vindictiveness of government officials who want rules to be followed just because they're 'the rules', specifics be damned.", 'The New York Sate Dept. Of Environmental Conservation killed this rescued squirrel and the rescued raccoon.', "The squirrel didn't have rabies shots and bit someone. The only reliable way to test for rabies is to (kill the animal and) test brain tissue.\n\nThis is why you need to vaccinate your pets.", 'They said they tested it first rabies. The inly way to do that us to kill the animal and test their brain tissue.', 'He wanted instagram influencer cash too.', 'The problem is that you\'re not seeing the bigger picture.  Without this law, NY\'s wildlife would absolutely be exploited for profits. Nothing would stop a person or company from mass trapping of animals to sell as pets. \n\nThis law stems from the same set of laws that made it illegal to sell wild game. Because people almost killed every single buffalo in existence trying to make money. \n\nIt\'s not about "a few people having pet squirrels", it\'s about protecting the balance of our natutal wildlife.', "You have no idea what you are talking about. The law they broke has nothing to do with rabies. The possession of wild animals native to NY is illegal while residing in the state of NY. You can own wild animals as pets in NY. As long as they can't be found wild in the state. For example, you can own a Fenec Fox, but you cannot own a Red Fox. Some other exotics have other rules too, but that's the basics.", 'What monsters', 'Respectfully, go eat a dick.', "Agreed, can't believe they didn't vaccinate their pets.", "By that logic, if we allow hunting of animals, nothing will stop a person or company from mass trapping of animals to sell as meat.\n\nRemember that this guy didn't buy or sell captured squirrels. He had one, that he himself found.\n\nThere are a thousand regulatory regimes that could achieve the benefits you describe without also leading to this sort of ridiculous overreach.", 'Wrong again, it is illegal to buy or sell wild game meat in the entire US for that exact reason.', 'You can also go to the governors site and raise a polite complaint there about the conduct of the NYS DEC.', "Did you read what I wrote?\n\nHis situation is not equivalent to buying or selling wild game meat.\n\nIt's equivalent to eating meat you hunted yourself. He didn't buy Peanut from someone else.", 'so then why was it necessary to single out this one man and his ostensibly harmless pet?', "No it's not. Because hunting meat is legal, what he did is illegal. \n\nIt would have been no problem if he had his hunting license, shot the sqirrel and ate it. \n\nBy keeping the squirrel as a pet, he broke the law, so no, they are not even close to equivalent.", 'Squirrels do not have a live rabies virus vaccine, but yes. This is why following procedures like wildlife quarantine (the raccoon was exposed to all the other animals and humans) and getting them to a licensed rehabber is really vital.', 'Hunting is legal, but selling game meat isn\'t. Hence, we have hunters without having widespread commercial exploitation of wild animals for meat.\n\nWhy can\'t we do the same thing for captive ownership? _That\'s_ the equivalence I\'m making.\n\nDoesn\'t make much sense to respond to someone saying "the laws need to change" with "but what happened is against the law".', 'Stop victim blaming. This is why you don\'t invade someone\'s house and start grabbing at their animals. "If only that squirrel hadn\'t been dressed so slutty it wouldn\'t have been euthanized"', "It's wild to compare an illegally captured unvaccinated squirrel to a rape victim.", 'Squirrels also do not carry rabies. A ridiculous situation all-around.', ">Lol. So then you would be ok if someone wanted to keep tigers or wolves as pets innurban areas, right?\n  \nHell, we might as well throw 'em into the mix. We already have to deal with pitbulls being legal to keep as pets.", 'He chose to do something illegal when a perfectly legal option existed.  The squirrel paid the price.  This is all on him.', 'I was thinking that as well, but giving the benefit of the doubt.', 'Amazing counter argument.', "Use common sense\n\nIf the squirrel has rabies, then the owner would've died from rabies already", "That's assuming the squirrel didn't get rabies recently. Which is illogical because the owner recently took in a raccoon that it didn't quarantine appropriately from the other animals. \n\nThis all could have been avoided if the owners followed basic safety precautions.", 'Lol unvaccinated squirrel. You sound retarded', 'You’re the type to call the gestapo on Anne frank living in an attic.', 'Idk presumably because he was breaking the law and someone reported him. I’m not saying the DEC response was the right one or not, but they certainly enforce laws related to wildlife on a regular basis.. My comment was more about the level of public outcry over it. Seems a bit over the top.', "Thank god for that law. I mean, if the government couldn't invade your home and kill your pets, our society could fall apart.", 'terminal reddit-brain', 'A bit of it, maybe, but the whole situation also highlights the absurdity of these sorts of wildlife laws, which is my main point here.', 'Ah yes, government overeach and execution of family members is why.', 'What a comparison', 'You need to get a license to hunt, just like this guy needed to get an animal rehab license. \n\nDo you think the government is just okay with poaching?', 'Found the dem', 'The only thing I hope is that the person that felt the need to “save” this “exploited” squirrel is happy at this outcome. Jesus Christ, get a life. All the trauma for some freaking Karen.', 'It’s trust factor is way too high for a wild animal now. He probably thought w.e animal that ate his tail just wanted to play like the animals at the people’s house.', 'And he’s spent at least 100,000 dollars a year on the animals at his home because the instagram cash makes it possible. It’s funny that you all think he’s bad when it wasn’t a veterinarian that turned them in(you know the one they take animals too).It was some random retarded photographer from Texas.', 'Comparing tigers and wolves to squirrels only makes you look even more inept. Weiner dogs are the most aggressive dog in the world, you don’t see countries banning them like XL Bully’s or pitbulls.', 'I know a guy who’s shot about 5 deer out of season. And he lives in an urban area.', 'Eastern Gray squirrels are native to the entire Eastern half of America and are in the least concerned category of endangerment. Even if the squirrel started running west the moment it was could walk it would die before it got out of his natural habitat lol.', 'Doesn’t work out as well if you post it on insta and become a poaching influencer', 'NYC has thousands of homeless and crimes that garner public attention but large resources were used for a squirrel?', 'Lol... what?', 'I hope that you get caught every “illegal” thing  that you do for the rest of your life… seriously. Get fucked', 'He had a permit this entire time. It briefly expired. This obviously warrants the death penality in your fucked up little hit. If you leave a bill unpaid for a day, i hope the court sentences you real fast.', 'Do you think animals just raise themselves? For free?', '“Being a responsible adult is too much work, so that makes it an unreasonable demand!”\n\nAs someone who took all the proper steps to be qualified to work with wildlife and ensure their safety, I’m here to tell you: its not that hard to do. All this guys had to do was make sure his permit was up to date (again, not even that hard), but he couldn’t even do the bare minimum. *Then* his irresponsible ass brought in a wild raccoon without knowing if it had rabies, couldn’t get any of them vaccinated, and then wonders why he got those animals taken from him? (Fun fact: the only way to test for rabies involves euthanizing them, because they have to check the brain tissue) Yeah, sorry, this idiot is 100% at fail here; he’s lucky he didn’t cause a viral outbreak with his irresponsible actions.\n\nThe reason these protocols are set up in the first place is because some dumb asshole like him fucked up massively and ruined it for everybody else; the *least* this dude could have done is not made that same mistake.', "I'm not stupid enough to plaster it all over social media... for profit I might add.", "I can't find anything saying he had a permit to have the squirrel.  Everything I find says otherwise.", 'Go to the influencers page and tell him he was wrong.', 'No the state was wrong.', "I disagree.  Good day, sir. You're dismissed.", 'Jesus Christ your miserable', 'Mods, why did the other peanut thread get locked and hidden?', 'It’s a squirrel guys…', 'Bad decision. People will literally go to war for their animals. If some government agent rolled up on me to take my dog away.. One of us ain’t walking away from that situation.', "I'm sorry but this is preposterous.\nMy wife is a licensed rehabber.\nShe cares for Squirrels multiple times a year.\nThere is a methodology to release and the idea of a squirrel returning is just a fable.\nPeanut was morbidly obese due to lack of proper nutrition and and had malocclusion of his teeth which is very painful due to not being kept in proximity to tree branches.\nThis animal was a cash cow for this pervert and was even used on his Onlyfans.\n\nhttps://www.bing.com/images/search?view=detailV2&ccid=c6ZAR3AF&id=996DFAFE5E949FAA0DAB25CA2E27A4DD8EA3217F&thid=OIP.c6ZAR3AFiBF8LR_fReE0yQHaGz&mediaurl=https%3a%2f%2fpbs.twimg.com%2fmedia%2fGFcc4V1XwAAOp3k.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.73a64047700588117c2d1fdf45e134c9%3frik%3dfyGjjt2kJy7KJQ%26pid%3dImgRaw%26r%3d0&exph=1102&expw=1200&q=squirrel+dad+only+fans&simid=608048493922287864&FORM=IRPRST&ck=228E374A8A9A5B9170F8F9B0CD05837D&selectedIndex=4&itb=0&ajaxhist=0&ajaxserp=0", "Guess there wasn't enough other crime occurring for the authorities to be taking care of.", 'And murdered.', 'Around 30k to be precise. That’s the total expenditure for this operation.', '30k???  WTH?', 'It was a day long raid with 5 agents. Plus all the expenses after the fact. \n\nThe agent that got bit should have had a rainbows vaccine so the my shouldn’t have needed to test the squirrel I’m the first place.', 'Damn.  Thanks for the information', 'This is outrageous. I feel so sorry for Pnut and Fred 😭', 'The DEC does not play. They can get warrants so fast and have arguably more authority than troopers', 'Merely using such language informs all of us of your seriously low IQ. Despicable.  As a grandmother of a disabled beautiful young lady I am disgusted.', "Dont forget the beagle puppies that Marshall tortures and sends to their deaths every year from their NY puppy factory farm. Why can't that go viral?"]


Post: Voting Registration Processing
Comments:
[]


Post: What To Do During While Visiting For The Marathon?
Comments:
[]


Post: Peanut the squirrel euthanized by DEC to test for rabies
Comments:

In [11]:
# group comments by post

# merge posts and comments on post name and link_id
merged = pd.merge(
    posts, 
    comments, 
    left_on='name', 
    right_on='link_id', 
    how='inner', 
    suffixes=('_post', '_comment')  # This renames _x and _y
)

merged

,_meta_post,all_awardings_post,allow_live_comments,approved_at_utc_post,approved_by_post,archived_post,author_post,author_flair_background_color_post,author_flair_css_class_post,author_flair_richtext_post,...,subreddit_name_prefixed_comment,subreddit_type_comment,top_awarded_type_comment,total_awards_received_comment,treatment_tags_comment,unrepliable_reason,ups_comment,user_reports_comment,editable,author_cakeday_comment
0,{'retrieved_2nd_on': 1730599759},[],False,NaN,NaN,False,Rinoremover1,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,17,[],NaN,NaN
1,{'retrieved_2nd_on': 1730599759},[],False,NaN,NaN,False,Rinoremover1,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,11,[],NaN,NaN
2,{'retrieved_2nd_on': 1730599759},[],False,NaN,NaN,False,Rinoremover1,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,19,[],NaN,NaN
3,{'retrieved_2nd_on': 1730599759},[],False,NaN,NaN,False,Rinoremover1,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,7,[],NaN,NaN
4,{'retrieved_2nd_on': 1730599759},[],False,NaN,NaN,False,Rinoremover1,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131084,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,8,[],NaN,NaN
131085,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
131086,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,1,[],NaN,NaN
131087,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,5,[],NaN,NaN
131088,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,r/newyork,public,NaN,0,[],NaN,3,[],NaN,NaN

overfitting on posts > finding posts that are irrelevant

In [12]:
import re

# have an LLM generate keywords? This is much faster

candidates = [
    "Zohran", "Mamdani", "Andrew Cuomo", "Cuomo", "Curtis Sliwa", "Sliwa", 
    "Eric Adams", "Brad Lander", "Adrienne Adams", "Scott Stringer", 
    "Zellnor Myrie", "Jessica Ramos", "Jim Walden"
]

events_and_parties = [
    "Ranked Choice", "RCV", "Fight and Deliver", "WFP", "Working Families Party",
    "Mayoral Election", "Democratic Primary", "June 24", "November 4"
]

policies = [
    "Rent freeze", "fare-free buses", "free childcare", "public supermarkets",
    "congestion pricing", "Department of Community Safety"
]

# Combine and escape (to handle special characters)
all_terms = candidates + events_and_parties + policies
pattern_string = r"(?i)\b(" + "|".join(map(re.escape, all_terms)) + r")\b"

# Create the compiled regex
election_regex = re.compile(pattern_string)


merged['is_election_related'] = (
    merged['title'].str.contains(election_regex, na=False) | 
    merged['selftext'].str.contains(election_regex, na=False)
)

# Filter for the relevant rows
df_2025_filtered = merged[merged['is_election_related']].copy()

/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_5323/970100265.py:30: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merged['title'].str.contains(election_regex, na=False) |
/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_5323/970100265.py:31: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merged['selftext'].str.contains(election_regex, na=False)

In [13]:
df_2025_filtered['title']

2239      Today is the last day of Early Voting in New Y...
2240      Today is the last day of Early Voting in New Y...
2241      Today is the last day of Early Voting in New Y...
2242      Today is the last day of Early Voting in New Y...
2243      Today is the last day of Early Voting in New Y...
                                ...
131084    Meet the ex-McKinsey exec helping NYC's CEOs g...
131085    Meet the ex-McKinsey exec helping NYC's CEOs g...
131086    Meet the ex-McKinsey exec helping NYC's CEOs g...
131087    Meet the ex-McKinsey exec helping NYC's CEOs g...
131088    Meet the ex-McKinsey exec helping NYC's CEOs g...
Name: title, Length: 30353, dtype: str

In [14]:
filtered = list(df_2025_filtered['title'].unique())
filtered

['Today is the last day of Early Voting in New York!',
 'Cuomo Objects to Plan to Shut Down the A Train for 4 Months - The New York Times',
 '2 people killed in New York City stabbing spree at 3 different Manhattan locations',
 'Former New York Gov. Andrew Cuomo set to sue accuser for defamation over sex harassment claims',
 'Former chief adviser to Eric Adams indicted in $100,000 bribery scheme',
 'The Battle Over NYC Congestion Pricing',
 'NYC Traffic After Congestion Pricing ',
 'Leading Eric Adams challenger will miss first matching funds payment after Adams ordered the payment not to go out',
 'Eric Adams’ troubles pile up, just as he get his post-indictment footing',
 'The Working Families Party’s election strategy: Don’t rank Eric Adams',
 'Far Reich Wing Eric Adams orders Trump Judge to let him attending Trump inauguration',
 'Far Reich Wing Racist Eric Adams brushes off poll of Cuomo leading: ‘We don’t say Mayor Stupid Chinkie Yang’',
 'Justice Dept. Is Said to Discuss Dropping Case Against Eric Adams',
 'REMINDER: Party Change Deadline is 2/14',
 'Justice Department orders charges against NYC Mayor Eric Adams dismissed',
 'Register to vote by tomorrow Feb 13th!',
 'Three top federal prosecutors resign after refusing to drop Adams charges',
 'New York City Mayor Eric Adams tried to get out of his bribery case by offering a bribe, ex-prosecutor says',
 "AOC Says Eric Adams Is Endangering NYC And Should 'Be Removed' From Office",
 'Justice Department moves to dismiss Eric Adams case after extraordinary internal revolt',
 'Judge orders Mayor Eric Adams, DOJ lawyers to appear in court to explain case dismissal request',
 'Mayor Eric Adams rallies against criticism at Ocean Hill church, tells supporters he’s ‘going nowhere’ • Brooklyn Paper',
 'Trump brags about killing congestion pricing to punish NYC and calls himself King.',
 'DOJ officials defends alleged quid pro quo with NYC mayor Eric Adams as judge hauls prosecutors to court to discuss case',
 'NYC congestion pricing tolls staying on after Trump administration moves to end the program',
 'New York governor to announce new oversight on Eric Adams administration - but will not remove him from office',
 "Federal judge wants 'adversarial' review of NYC Mayor Eric Adams-DOJ deal",
 'A Cuomo Comeback? Former NY Governor Eyes NYC Mayor Run',
 'Hochul says she will stand down in fight Trump on congestion pricing',
 'NYC Mayor Eric Adams to close Roosevelt Hotel migrant center targeted by Musk, Trump administration',
 'NYC Mayor Eric Adams claims prosecutorial misconduct, asking judge to dismiss criminal case',
 "New York's congestion pricing plan is working great — Trump wants to destroy it",
 'Feds give MTA deadline to kill NYC congestion pricing tolls',
 'After laying groundwork for months, Andrew Cuomo is said to enter the race for New York City Mayor',
 'The case of the missing $300M: Eric Adams’ campaign finance woes grow',
 'Report: Cuomo could enter NYC mayor’s race this weekend',
 'Former N.Y. Gov. Andrew Cuomo launches NYC mayoral campaign',
 'Former Gov. Andrew Cuomo launches a run for New York City mayor',
 'Cuomo takes aim at progressives, police funding at Manhattan campaign stop',
 "House Democrats investigate Justice Department's decision to drop Eric Adams charges",
 "As mayoral candidate Andrew Cuomo slams NYC, Eric Adams doesn't take the bait",
 'Majority says Eric Adams should resign as NYC mayor: Survey',
 'NYC’s Congestion Pricing Is Good for the US',
 'Federal prosecutors who worked on the Eric Adams case escorted out of workplace',
 'Cuomo scandals cost NY taxpayers nearly $60 million in legal fees, comptroller review finds',
 'New poll shows how New Yorkers feel about congestion pricing',
 'Siena poll: Hochul leads Democratic primary by a lot',
 'Cuomo dominates NYC mayoral opponents with $3 million haul',
 'New York City paying $500,000 a month to indicted developer who could testify against Mayor Eric Adams',
 'Feds give MTA 30-day extension on congestion pricing',
 'New Yorkers See a City in Crisis. Are They Ready for a Cuomo Comeback?',
 'Cuomo Leads NYC Mayor’s Race With 39%, Mamdani at 15%, All Other Candidates in Single Digits',
 'Is mayoral candidate Andrew Cuomo beholden to Donald Trump?',
 'Judge throws out Eric Adams corruption case and sides with Trump’s DOJ',
 'NYC Mayor Eric Adams corruption case dismissed with prejudice, judge rules',
 'Adams to skip New York City’s Democratic primary, run for reelection on nonpartisan line',
 'Eric Adams running as independent in NYC mayor race',
 'Queens Democrats continue to line up behind Cuomo for mayor',
 'MTA and feds push congestion pricing cancelation deadline back',
 'MTA, feds reach agreement that could keep NYC congestion pricing tolls in place into the fall',
 'Billy Joel donates $50K to super PAC backing Andrew Cuomo’s mayoral bid — Barry Diller kicks in $250K',
 'Cuomo leading polling for Mayor',
 "Congestion pricing is working': MTA says tolls keeping 82k drivers a day out of Manhattan",
 'Andrew Cuomo Slams AOC’s Rally Tour for ‘Capitalizing’ on Voters’ Trump Fears',
 'NY settles sexual harassment lawsuit with former aide to Andrew Cuomo',
 'Self-identifying ‘hot girls’ are mobilizing to elect a progressive as New York City mayor | Inspired by ‘Hot Girls for Bernie’, a grassroots campaign is rallying behind the democratic socialist Zohran Mamdani',
 'N.Y. governor says congestion pricing will remain despite federal deadline to end the program Sunday',
 "Feds threaten NYC highway money if MTA doesn't shut down congestion pricing",
 'Three prosecutors in Eric Adams case quit, claiming they were being pressured to admit ‘regret and wrongdoing’',
 'Feds accidentally publish secret plan to kill NYC congestion pricing',
 "Andrew Cuomo penalized $622K in NYC mayor's race for coordinating with big-money group",
 'What If New York Ditched Income Tax? Let’s Talk Pros, Cons, and Cold, Hard Reality',
 "Trump DOJ launches criminal probe into Andrew Cuomo over 'COVID cover-up'",
 'Mayor Eric Adams wants $402M of public money to upgrade 5th Avenue shopping district',
 "NYC Council Speaker Adrienne Adams rips Cuomo on anniversary of her dad's COVID-19 death",
 'Latest NYC congestion pricing deadline comes and goes, tolling remains in effect',
 'Judge halts Trump administration effort to ax New York congestion pricing',
 "New Yorkers how worried are y'all about your state's shift ward to the right",
 'For the love of all things holy, please help STOP Cuomo.',
 'Mamdani ranks first in Working Families Party’s picks for NYC mayor',
 'Inside Cuomo’s State-Funded Legal War Against the Women Who Accused Him of Sexual Harassment',
 'Far Reich Wing Adams takes a page out of his gods cadet bonespurs book attacks Cuomo’s track record from City Hall lectern and bashes him',
 'Alexandria Ocasio-Cortez Endorses Zohran Mamdani as Top Choice for Mayor',
 'Hey New Yorkers. Wanna give all your money to israel? Wanna prioritize israel 1st & New York 2nd?? Vote everyone else including Cuomo.',
 'Jessica Ramos Will Endorse Andrew Cuomo for New York City Mayor',
 'Michael Bloomberg Endorses Andrew Cuomo for Mayor',
 'Correction: He [Cuomo] LIED TO us before. He’ll do it again!',
 'Eric Adams calls for broader protest mask ban in NYC after ‘No Kings’ march',
 'NYC mayoral candidate Brad Lander arrested by masked agents at immigration court',
 'Full video of the Brad Lander arrest from the campaign.',
 'Bernie Sanders endorses Zohran Mamdani for NYC mayor',
 'Brad Lander: NYC mayoral candidate released after arrest by immigration officers | CNN',
 'Former critics who once demanded Cuomo resign are now endorsing him.',
 'Volunteers Needed for Election Protection - New York Race!!',
 'Cuomo Halted Investigation Into Weinstein Case After $25K Donation From His Former Lawyer',
 "Cuomo had a chance to fix corruption in NYS once, but stopped when it got too close to his inner circle. What the shutting down of the Moreland Comission says about Cuomo's style of governance.",
 'Bill Clinton Endorses Andrew Cuomo For NYC Mayor',
 'NYC mayor candidate Brad Lander trots out Cuomo’s harassment accusers in final campaign push after ICE arrest',
 'Colbert grills NYC mayoral candidate Zohran Mamdani on his Israel views ahead of primary vote',
 'New Yorkers vote in mayoral primary as poll shows Mamdani leading Cuomo',
 'Zohran Mamdani set to topple Andrew Cuomo in NYC mayoral race',
 'as somebody who does not live in New York, I want Eric Adams to win the NYC mayoral race.',
 "Anyone else find it kind of funny that New York's third congressional districts history kind of went like this the past couple years",
 'Stefanik Attacks Mamdani as ‘Terrorist Sympathizer’ in Fundraising Email Before NYC Race Even Called: ‘Truly Makes Me Sick’',
 "Mamdani's win in New York isn't surprising; everybody hates Cuomo (who had to resign previously due to sexual harassment allegations)",
 'Can anyone elaborate on why Cuomo did so well in the Bronx?',
 'Rep Malliotakis wants Trump to “step in” to keep us safe',
 "Michaela Kennedy-Cuomo Reacts to Dad Andrew Cuomo's Surprise NYC Election Loss",
 'Crowd jeers Trump-friendly Mayor Adams as ‘criminal’ at reelection campaign launch against Dem ‘socialist’ Mamdani',
 'Republicans and right-wing media have already suggested siccing their mask-wearing brownshirt thugs on Zohran Mamdani. How should the state respond if they do?',
 "I don't like Zohran Mamdani. (I don't live in New York.)",
 'Eric Adams says Zohran Mamdani was born with a ‘silver spoon’ as he launches reelection campaign',
 'Economists Support Zohran Mamdani’s Plan for New York City',
 'Two major NYC unions back Mamdani’s general election bid for mayor',
 'Zohran Mamdani plans to impose a tax on all NYC millionaires and billionaires — and they aren’t taking it too well',
 'CNN panelist calls Mamdani a ‘Muslim AOC’ and says Democrats have ‘death wish’ for tapping him as NYC mayor',
 'Mamdani confronted by pro-Palestinian activist over Israel comments',
 'STUPID NIGGER MONKEY TOKEN Questions Faith of Any Jews Supporting Zohran Mamdani And Says They Should Go To Camp To Concentrate And Use The Showers',
 'Eric Adams, surrounded by faith leaders, officially launches his reelection campaign',
 'Zohran Mamdani Wins N.Y.C. Mayoral Primary in Decisive 12-Point Victory',
 "With the help of the Far Riech Wing Governor And Far Reich Wing Mayor NYC elites hatch plan to stop 'Trojan Horse' Zohran Mamdani as mayor and steal the election",
 'With the help of the Far Riech Wing Governor And Far Reich Wing Mayor Andrew Cuomo staying on NYC mayoral election ballot — as critics slam ex-gov as ‘spoiler’ candidate',
 'Defiant GOP candidate Curtis Sliwa insists on staying in NYC mayoral race — despite calls to drop out, help Eric Adams beat Zohran Mamdani: ‘Exactly’',
 'Zohran Mamdani statement after Trumps threat and admission of helping Mayor Adams.',
 'Kirsten Gillibrand apologizes to Zohran Mamdani over ‘jihad’ claim',
 'MTA NTC Transit Police?',
 "We should be fighting for the rights of those who DON'T have enough to live. Not for billionaires.",
 "Excuse me, I'm not from New York but I want to educate myself.",
 'Mamdani’s win over Cuomo reshapes NYC political landscape',
 'New York Times Grants Race Science Enthusiast Anonymity in Mamdani Hit Piece',
 'Debunking All the B.S. About Zohran Mamdani',
 'I support Mamdani and hope that he wins. But -',
 'Paterson calls on leaders to come together to defeat Mamdani in NYC mayoral election',
 'Trump booster Charlie Kirk calls NYC mayoral candidate Mamdani a ‘parasite’ and says legal immigration ‘also the problem’',
 'So they’re ganging up on Mamdani because of course they would',
 'Former Gov. Andrew Cuomo staying in NYC mayoral race as an independent, sources say',
 "Eric Adams loses lawsuit against local election body — and his team claims 'WOKE' Democrats stole it",
 "Among wealthy Manhattanites, Eric Adams wins the most-popular vote unless 'WOKE' Democrats teal it",
 'New York Mayor Eric Adams Led Criminal Enterprise at NYPD',
 'Lawsuits dredge up messy NYPD era under Eric Adams as he begins reelection bid',
 'As food prices rise, Mamdani wants public grocery stores in New York. Can it work? | Zohran Mamdani | The Guardian',
 'A Stunning Number of Voters Didn’t Rank Andrew Cuomo for Mayor',
 'The number of New Yorkers that prefer calling it the Mario Cuomo bridge instead of the Tappan Zee is still zero, right?',
 'New NYC election poll shows huge leads for Mamdani: Mamdani 50, Cuomo 22, Sliwa 13, Adams 7. Mamdani leads among all races, all income brackets, all education levels, all age groups except 55+, and all boroughs except Staten Island. Odd crosstabs: Mamdani performs worse among women & union members.',
 'Limited Access Exposed: Socialist Candidate Zohran Mamdani’s Opulent Wedding in Uganda Raises Eyebrows',
 'Why is nobody giving eric Adams a chance in the New York city election?',
 'Donald Trump and Andrew Cuomo Secretly Talked on the Phone as Trump Weighs Endorsement in N.Y.C. Mayoral Race: Report',
 "Andrew Cuomo ridiculed after ‘nepo baby’ tweet challenging Zohran Mamdani to ‘heavyweight bout'",
 'Updated NYC mayoral election polling average (DDHQ): Mamdani (D) 39%, Cuomo 25%, Sliwa (R) 15%, Adams 11%, Walden 1%. In latest Siena poll, Zohran Mamdani leads among all income brackets, all religions except Judaism, all age groups except 55+, and all races except Black; Cuomo leads in these demos.',
 'Silicon Valley Is Panicking About Zohran Mamdani. NYC’s Tech Scene Is Not',
 "Mamdani Pounces as Leaked Audio Shows Cuomo 'Expecting Trump's Help' to Win",
 "cuomo is hoping for trump's help in winning governors race",
 "cuomo seeks trump's aid in political race",
 'New York Democrats on the verge of botching yet another congressional redistricting effort',
 'Mamdani raises over $1M in latest NYC fundraising haul, drowning out Cuomo, Adams',
 'Vance goes after NYC mayoral hopeful Mamdani: ‘He should show more gratitude to the United States’',
 'Another poll of Jewish voters in NYC mayoral election puts Mamdani in the lead: Mamdani (D) 37%, Adams 25%, Cuomo 21%, Sliwa (R) 14%. Mamdani leads among Reform Jews and non-denominational Jews; Cuomo leads among Conservative Jews, and Adams leads among Orthodox Jews. (GQR/NYSN, 800 RV, MOE = 3.46%)',
 'Is Congestion Pricing Working? The MTA’s Revamped Data Team Is Figuring It Out',
 "Mamdani calls reports of White House meddling in NYC mayor's race an 'affront to our democracy' | Trump advisers reportedly discussed jobs for Adams and Sliwa.",
 'What can Mamdami do as mayor?',
 'In all polls since his primary victory, Mamdani has led in all income brackets polled. In the most recent poll (Pulse, 638 LV, MOE 4%), Mamdani leads 31-26 among the lowest earners (<$25,000 bracket), and 37-26 among the highest earners (>$150,000 bracket); Cuomo trails consistently in second place.',
 'Cuomo Pins 9/11 On Mamdani',
 'Chuck Schumer Meets With Mamdani but Refuses to Endorse Him',
 "Eric Adams' approval rating drops to 17%, a record low. 70% disapprove, including 70% of Blacks and 83% of Latinos. Adams remains a registered Democrat, but he suffers a worse disapproval rating among Democrats (73%) than Republicans (52%). 99% of WFP voters disapprove. [Public Policy Polling]",
 'After a flurry of new polls, Mamdani reaches his best-ever lead in the polling average, Adams sinks to a new low: Mamdani (D) 43%, Cuomo 25%, Sliwa (R) 14%, Adams 10% [DDHQ]. In latest poll, Mamdani also leads 47-40 in a head-to-head against Cuomo, and 52-28 in a head-to-head against Sliwa [Emerson]',
 "9/12/25👺Eric Adams' approval rating drops to 17%(remains a registered Democrat)🇺🇸🙏",
 'Opinion | Kathy Hochul: Why I Am Endorsing Zohran Mamdani',
 'Trump Warns of Financial Penalties After Hochul Endorses Mamdani',
 'Trump slams Hochul over endorsement of Mamdani for mayor',
 'New NYC election poll: Mamdani (D) 43%, Cuomo 28%, Sliwa (R) 15%, Adams 6% [YouGov/CBS, 1901 LV, MOE 2.6%]. -Adams: Mamdani 44%, Cuomo 30%, Sliwa 17%. Mamdani leads among all races, all education levels, all age groups except 65+, and among both men and women. Adams suffers his worst poll result yet',
 'New Yorkers are lukewarm about using RCV for general elections—just 42% of NYC Democratic primary voters want RCV in general elections, while 51% are opposed. Opposition is stronger among self-described moderates (63%), even though RCV is believed to help moderate candidates (e.g. Cuomo) get elected',
 'New NYC mayoral poll shows Mamdani beating Cuomo by 10 points in head-to-head matchup',
 'Mamdani declines to immediately back Hochul’s reelection after she offers him coveted endorsement',
 'N.Y. Assembly Speaker Carl Heastie, another major Dem holdout, set to endorse Mamdani for NYC mayor',
 'Mamdani leads in another poll of NYC Jews: Mamdani 35, Cuomo 32, Adams 17, Sliwa 13. Notably, Mamdani leads among Protestants but trails among Catholics: Cuomo 32, Sliwa 26, Mamdani 25, Adams 10. In a H2H vs Cuomo, Mamdani trails among Jews, Protestants, and Catholics, but still wins 47-39 overall.',
 'More New York Democrats coalesce behind Zohran Mamdani, but key holdouts remain',
 "Zohran Mamdani's been called a communist who'll defund the police. Here's where he actually stands",
 'Eric Adams: Gen Z backers of Mamdani are ‘radicalized, hate US’',
 'Andrew Cuomo heckled during campaign event at Queens mosque',
 "Kamala Harris gives Zohran Mamdani a tepid endorsement: 'I endorse the Democrat in the race'",
 'Mamdani enjoys 20-point lead in new Suffolk poll: Mamdani 45%, Cuomo 25%, Sliwa 9%, Adams 8% (500 LV, MOE 4%). Mamdani leads among all income brackets, all education levels, all races, all age groups, all boroughs, and among both men and women. 33% believe Cuomo would commit sexual assault again.',
 'Zohran Mamdani’s proposals are bold, but are they realistic for NYC?',
 "Republican New York Mayoral Candidate Curtis Sliwa on Wednesday accuses Andrew Cuomo-allied Billionaires tried to Bribe him to drop out of Mayor's race",
 'Transit union endorses Cuomo’s bid for mayor, rebukes Mamdani’s free bus proposal',
 'New York City’s Suburbs Heat Up as Residents Move in Anticipation of a Mamdani Win',
 'Eric Adams drops out of the New York city mayoral race',
 'Eric Adams Abandons Re-election Bid for Mayor of New York City',
 'Eric Adams out of NYC Mayor election. Zohran Mamdani vs Andrew Cuomo for New York Mayor Election: Who will win?',
 'Mamdani fires back after Trump threatens to cut federal funding for NYC if he wins mayoral race',
 'Mamdani Says He Would Phase Out N.Y.C. Gifted Program for Early Grades',
 "Cuomo tells 'The View' a Mamdani win would be 'gift' for Trump, lead to NYC takeover",
 'New poll finds Mamdani outstrips Cuomo 2:1 among NYC Latinos in mayoral race',
 'Mamdani’s stance on Israel isn’t an attack on Netanyahu, it’s an antisemitic affront to Jews',
 'Mamdani education plan would focus on helping NYC homeless students',
 'Cuomo climbs 10% in new poll, but still trails Mamdani after Adams’ NYC mayoral race exit',
 'Mamdani blasts Cuomo’s response to Trump DOJ charges against AG Letitia James',
 'Cuomo calls for more specialized high schools amid controversy over Mamdani education stance',
 'Zohran Mamdani makes his case to Jewish New Yorkers at Congregation Beth Elohim',
 'Hochul says she’s aligned with Mamdani on universal childcare, but at odds over funding',
 'Zohran Mamdani Is a Good Man, But He’s Not the Mayor NYC Needs Right Now',
 "Zohran Mandani's Got Big Ideas, But NYC Needs a Mayor Who Can Deliver",
 'Many swings, few knockouts as Cuomo, Mamdani and Sliwa trade jabs in NYC mayoral debate',
 'Mamdani, Sliwa gang up on Cuomo in testy NYC mayoral debate',
 'NYC business leaders drop $3 million over two days into mayoral race in bid to stop Mamdani',
 "Andrew Cuomo is still behind — and he’s blaming 'WOKE' Democrats",

In [15]:
len(list(df_2025_filtered['title'].unique()))

240

In [16]:
df_2025_filtered

,_meta_post,all_awardings_post,allow_live_comments,approved_at_utc_post,approved_by_post,archived_post,author_post,author_flair_background_color_post,author_flair_css_class_post,author_flair_richtext_post,...,subreddit_type_comment,top_awarded_type_comment,total_awards_received_comment,treatment_tags_comment,unrepliable_reason,ups_comment,user_reports_comment,editable,author_cakeday_comment,is_election_related
2239,{'retrieved_2nd_on': 1730767337},[],False,NaN,NaN,False,cypothingy,,NaN,[],...,public,NaN,0,[],NaN,8,[],NaN,NaN,True
2240,{'retrieved_2nd_on': 1730767337},[],False,NaN,NaN,False,cypothingy,,NaN,[],...,public,NaN,0,[],NaN,5,[],NaN,NaN,True
2241,{'retrieved_2nd_on': 1730767337},[],False,NaN,NaN,False,cypothingy,,NaN,[],...,public,NaN,0,[],NaN,7,[],NaN,NaN,True
2242,{'retrieved_2nd_on': 1730767337},[],False,NaN,NaN,False,cypothingy,,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
2243,{'retrieved_2nd_on': 1730767337},[],False,NaN,NaN,False,cypothingy,,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131084,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,public,NaN,0,[],NaN,8,[],NaN,NaN,True
131085,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
131086,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
131087,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,public,NaN,0,[],NaN,5,[],NaN,NaN,True
131088,{'retrieved_2nd_on': 1762132382},[],False,NaN,NaN,False,thisisinsider,NaN,NaN,[],...,public,NaN,0,[],NaN,3,[],NaN,NaN,True

In [17]:
print(list(merged.columns))

['_meta_post', 'all_awardings_post', 'allow_live_comments', 'approved_at_utc_post', 'approved_by_post', 'archived_post', 'author_post', 'author_flair_background_color_post', 'author_flair_css_class_post', 'author_flair_richtext_post', 'author_flair_template_id_post', 'author_flair_text_post', 'author_flair_text_color_post', 'author_flair_type_post', 'author_fullname_post', 'author_is_blocked_post', 'author_patreon_flair_post', 'author_premium_post', 'awarders_post', 'banned_at_utc_post', 'banned_by_post', 'can_gild_post', 'can_mod_post_post', 'category', 'clicked', 'content_categories', 'contest_mode', 'created_post', 'created_utc_post', 'discussion_type', 'distinguished_post', 'domain', 'downs_post', 'edited_post', 'gilded_post', 'gildings_post', 'hidden', 'hide_score', 'id_post', 'is_created_from_ads_ui', 'is_crosspostable', 'is_meta', 'is_original_content', 'is_reddit_media_domain', 'is_robot_indexable', 'is_self', 'is_video', 'likes_post', 'link_flair_background_color', 'link_flair_css_class', 'link_flair_richtext', 'link_flair_text', 'link_flair_text_color', 'link_flair_type', 'locked_post', 'media', 'media_embed', 'media_only', 'mod_note_post', 'mod_reason_by_post', 'mod_reason_title_post', 'mod_reports_post', 'name_post', 'no_follow_post', 'num_comments', 'num_crossposts', 'num_reports_post', 'over_18', 'permalink_post', 'pinned', 'post_hint', 'preview', 'pwls', 'quarantine', 'removal_reason_post', 'removed_by', 'removed_by_category', 'report_reasons_post', 'retrieved_on_post', 'saved_post', 'score_post', 'secure_media', 'secure_media_embed', 'selftext', 'send_replies_post', 'spoiler', 'stickied_post', 'subreddit_post', 'subreddit_id_post', 'subreddit_name_prefixed_post', 'subreddit_subscribers', 'subreddit_type_post', 'suggested_sort', 'thumbnail', 'thumbnail_height', 'thumbnail_width', 'title', 'top_awarded_type_post', 'total_awards_received_post', 'treatment_tags_post', 'ups_post', 'upvote_ratio', 'url', 'url_overridden_by_dest', 'user_reports_post', 'view_count', 'visited', 'wls', 'crosspost_parent', 'crosspost_parent_list', 'poll_data', 'gallery_data', 'is_gallery', 'media_metadata', 'author_cakeday_post', '_meta_comment', 'all_awardings_comment', 'approved_at_utc_comment', 'approved_by_comment', 'archived_comment', 'associated_award', 'author_comment', 'author_flair_background_color_comment', 'author_flair_css_class_comment', 'author_flair_richtext_comment', 'author_flair_template_id_comment', 'author_flair_text_comment', 'author_flair_text_color_comment', 'author_flair_type_comment', 'author_fullname_comment', 'author_is_blocked_comment', 'author_patreon_flair_comment', 'author_premium_comment', 'awarders_comment', 'banned_at_utc_comment', 'banned_by_comment', 'body', 'can_gild_comment', 'can_mod_post_comment', 'collapsed', 'collapsed_because_crowd_control', 'collapsed_reason', 'collapsed_reason_code', 'comment_type', 'controversiality', 'created_comment', 'created_utc_comment', 'distinguished_comment', 'downs_comment', 'edited_comment', 'gilded_comment', 'gildings_comment', 'id_comment', 'is_submitter', 'likes_comment', 'link_id', 'locked_comment', 'mod_note_comment', 'mod_reason_by_comment', 'mod_reason_title_comment', 'mod_reports_comment', 'name_comment', 'no_follow_comment', 'num_reports_comment', 'parent_id', 'permalink_comment', 'removal_reason_comment', 'replies', 'report_reasons_comment', 'retrieved_on_comment', 'saved_comment', 'score_comment', 'score_hidden', 'send_replies_comment', 'stickied_comment', 'subreddit_comment', 'subreddit_id_comment', 'subreddit_name_prefixed_comment', 'subreddit_type_comment', 'top_awarded_type_comment', 'total_awards_received_comment', 'treatment_tags_comment', 'unrepliable_reason', 'ups_comment', 'user_reports_comment', 'editable', 'author_cakeday_comment', 'is_election_related']

In [18]:
merged['created_utc_post'] = pd.to_datetime(merged['created_utc_post'], unit='s')
merged['created_utc_comment'] = pd.to_datetime(merged['created_utc_comment'], unit='s')

In [19]:
filtered = merged[['title', 'body', 'ups_post', 'ups_comment', 'downs_post', 'downs_comment', 'created_utc_post', 'created_utc_comment']]
filtered = filtered[filtered['body'] != '[removed]']
filtered['body'] = filtered['body'].str.replace(r'\s+', ' ', regex=True).str.strip()
filtered['body'] = filtered['body'].str.lower()
filtered['title'] = filtered['title'].str.lower()
filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment
0,instagram-famous squirrel named peanut seized ...,totally unacceptable. shame on the anonymous m...,89,17,0,0,2024-11-01 14:09:11,2024-11-01 17:06:46
1,instagram-famous squirrel named peanut seized ...,"i agree. according to the article, the squirre...",89,11,0,0,2024-11-01 14:09:11,2024-11-01 17:11:07
2,instagram-famous squirrel named peanut seized ...,contact state dec and tell them they where wro...,89,19,0,0,2024-11-01 14:09:11,2024-11-01 17:13:10
3,instagram-famous squirrel named peanut seized ...,who do i call? the fact that they're not sayin...,89,7,0,0,2024-11-01 14:09:11,2024-11-01 17:15:33
4,instagram-famous squirrel named peanut seized ...,not entirely sure. your state legislator could...,89,1,0,0,2024-11-01 14:09:11,2024-11-01 17:18:09
...,...,...,...,...,...,...,...,...
131081,meet the ex-mckinsey exec helping nyc's ceos g...,"i remember 9 /11 i remember who funded it. so,...",175,-6,0,0,2025-10-31 17:43:29,2025-10-31 19:40:22
131082,meet the ex-mckinsey exec helping nyc's ceos g...,can't tell if good guy from article title,175,7,0,0,2025-10-31 17:43:29,2025-10-31 20:04:38
131084,meet the ex-mckinsey exec helping nyc's ceos g...,plays both sides so they always come out on top.,175,8,0,0,2025-10-31 17:43:29,2025-10-31 20:22:48
131087,meet the ex-mckinsey exec helping nyc's ceos g...,he’s running a pac so his goal is buy influenc...,175,5,0,0,2025-10-31 17:43:29,2025-10-31 22:00:40
131088,meet the ex-mckinsey exec helping nyc's ceos g...,lotta people out here grifting using zohran's ...,175,3,0,0,2025-10-31 17:43:29,2025-10-31 23:19:32

In [20]:
filtered 

detector = LanguageDetectorBuilder.from_languages(Language.ENGLISH).build()

def check_english(text):
    result = detector.detect_language_of(text)
    return result == Language.ENGLISH

filtered['is_english'] = filtered['body'].apply(check_english)
filtered = filtered[filtered['is_english'] == True]

In [21]:
filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment,is_english
0,instagram-famous squirrel named peanut seized ...,totally unacceptable. shame on the anonymous m...,89,17,0,0,2024-11-01 14:09:11,2024-11-01 17:06:46,True
1,instagram-famous squirrel named peanut seized ...,"i agree. according to the article, the squirre...",89,11,0,0,2024-11-01 14:09:11,2024-11-01 17:11:07,True
2,instagram-famous squirrel named peanut seized ...,contact state dec and tell them they where wro...,89,19,0,0,2024-11-01 14:09:11,2024-11-01 17:13:10,True
3,instagram-famous squirrel named peanut seized ...,who do i call? the fact that they're not sayin...,89,7,0,0,2024-11-01 14:09:11,2024-11-01 17:15:33,True
4,instagram-famous squirrel named peanut seized ...,not entirely sure. your state legislator could...,89,1,0,0,2024-11-01 14:09:11,2024-11-01 17:18:09,True
...,...,...,...,...,...,...,...,...,...
131081,meet the ex-mckinsey exec helping nyc's ceos g...,"i remember 9 /11 i remember who funded it. so,...",175,-6,0,0,2025-10-31 17:43:29,2025-10-31 19:40:22,True
131082,meet the ex-mckinsey exec helping nyc's ceos g...,can't tell if good guy from article title,175,7,0,0,2025-10-31 17:43:29,2025-10-31 20:04:38,True
131084,meet the ex-mckinsey exec helping nyc's ceos g...,plays both sides so they always come out on top.,175,8,0,0,2025-10-31 17:43:29,2025-10-31 20:22:48,True
131087,meet the ex-mckinsey exec helping nyc's ceos g...,he’s running a pac so his goal is buy influenc...,175,5,0,0,2025-10-31 17:43:29,2025-10-31 22:00:40,True
131088,meet the ex-mckinsey exec helping nyc's ceos g...,lotta people out here grifting using zohran's ...,175,3,0,0,2025-10-31 17:43:29,2025-10-31 23:19:32,True

In [22]:
filtered['comment_length'] = filtered['body'].apply(len)
filtered['title_length'] = filtered['title'].apply(len)

filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment,is_english,comment_length,title_length
0,instagram-famous squirrel named peanut seized ...,totally unacceptable. shame on the anonymous m...,89,17,0,0,2024-11-01 14:09:11,2024-11-01 17:06:46,True,73,75
1,instagram-famous squirrel named peanut seized ...,"i agree. according to the article, the squirre...",89,11,0,0,2024-11-01 14:09:11,2024-11-01 17:11:07,True,105,75
2,instagram-famous squirrel named peanut seized ...,contact state dec and tell them they where wro...,89,19,0,0,2024-11-01 14:09:11,2024-11-01 17:13:10,True,136,75
3,instagram-famous squirrel named peanut seized ...,who do i call? the fact that they're not sayin...,89,7,0,0,2024-11-01 14:09:11,2024-11-01 17:15:33,True,106,75
4,instagram-famous squirrel named peanut seized ...,not entirely sure. your state legislator could...,89,1,0,0,2024-11-01 14:09:11,2024-11-01 17:18:09,True,67,75
...,...,...,...,...,...,...,...,...,...,...,...
131081,meet the ex-mckinsey exec helping nyc's ceos g...,"i remember 9 /11 i remember who funded it. so,...",175,-6,0,0,2025-10-31 17:43:29,2025-10-31 19:40:22,True,66,80
131082,meet the ex-mckinsey exec helping nyc's ceos g...,can't tell if good guy from article title,175,7,0,0,2025-10-31 17:43:29,2025-10-31 20:04:38,True,41,80
131084,meet the ex-mckinsey exec helping nyc's ceos g...,plays both sides so they always come out on top.,175,8,0,0,2025-10-31 17:43:29,2025-10-31 20:22:48,True,48,80
131087,meet the ex-mckinsey exec helping nyc's ceos g...,he’s running a pac so his goal is buy influenc...,175,5,0,0,2025-10-31 17:43:29,2025-10-31 22:00:40,True,73,80
131088,meet the ex-mckinsey exec helping nyc's ceos g...,lotta people out here grifting using zohran's ...,175,3,0,0,2025-10-31 17:43:29,2025-10-31 23:19:32,True,93,80

In [23]:
filtered['comment_length'].mean()

np.float64(185.01051629491892)

In [24]:
filtered.to_csv('filtered_reddit_data.csv', index=False)