In [343]:
%pip install numpy

Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (2.4.2)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [344]:
%pip install lingua-language-detector

Requirement already satisfied: lingua-language-detector in /opt/homebrew/lib/python3.11/site-packages (2.1.1)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [345]:
import pandas as pd
import numpy as np
from lingua import Language, LanguageDetectorBuilder

In [346]:
posts = pd.read_csv('./r_AskALiberal_posts.csv')
posts

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,ups,upvote_ratio,url,user_reports,view_count,visited,wls,preview,post_hint,poll_data
0,{'retrieved_2nd_on': 1750769578},[],False,NaN,NaN,False,NextNefariousness125,NaN,NaN,[],...,1,1.00,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
1,{'retrieved_2nd_on': 1750769783},[],False,NaN,NaN,False,LemonySnacker,NaN,NaN,[],...,27,0.58,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
2,{'retrieved_2nd_on': 1750771025},[],False,NaN,NaN,False,Dangerous-Office7801,NaN,NaN,[],...,12,0.73,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
3,{'retrieved_2nd_on': 1750772665},[],False,NaN,NaN,False,NextRefrigerator6306,NaN,NaN,[],...,5,0.86,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
4,{'retrieved_2nd_on': 1750772718},[],False,NaN,NaN,False,Deadpan_Sunflower64,NaN,NaN,[],...,1,0.99,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,{'retrieved_2nd_on': 1762595975},[],False,NaN,NaN,False,LibraProtocol,NaN,NaN,[],...,1,1.00,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
318,{'retrieved_2nd_on': 1762596235},[],False,NaN,NaN,False,LibraProtocol,NaN,NaN,[],...,3,0.53,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
319,"{'edited_title': '[ Removed by moderator ]', '...",[],False,NaN,NaN,False,strugglingerdevelop,NaN,NaN,[],...,0,0.48,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,0.0
320,{'retrieved_2nd_on': 1762597637},[],False,NaN,NaN,False,Ok-Art-6451,NaN,NaN,[],...,1,1.00,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN
321,{'retrieved_2nd_on': 1762599612},[],False,NaN,NaN,False,NotSupposeToSpeak,NaN,NaN,[],...,1,1.00,https://www.reddit.com/r/AskALiberal/comments/...,[],NaN,False,7,NaN,NaN,NaN

In [347]:
posts["title"]

0               Coming to a balanced take on immigration
1      Why is that when Democrats lose, they must mov...
2      How do you deal with Immigrants that have come...
3      What foreign country do you think has the grea...
4      If I had voted either during the midterms, or ...
                             ...
317    Is it possible to criticize a culture without ...
318    Is it possible to criticize a culture without ...
319    Do you believe there was an Epstein List cover...
320    would y’all agree that bigotry did used to hav...
321               Will Republicans stand with a pervert?
Name: title, Length: 322, dtype: str

In [348]:
comments = pd.read_csv('./r_AskALiberal_comments.csv')

/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_79014/2490558708.py:1: DtypeWarning: Columns (0: collapsed_reason, 1: removal_reason) have mixed types. Specify dtype option on import or set low_memory=False.
  comments = pd.read_csv('./r_AskALiberal_comments.csv')

In [349]:
posts.iloc[:1]['name']

0    t3_1li3dq7
Name: name, dtype: str

In [350]:
comments.iloc[:1]['link_id']

0    t3_1lhh8uj
Name: link_id, dtype: str

In [351]:
# for the first 10 posts, find all comments
first_10_posts = posts.iloc[:10]['name']
first_10_comments = comments[comments['link_id'].isin(first_10_posts)]
first_10_comments

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,subreddit_name_prefixed,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,ups,user_reports,author_cakeday,editable
71,{'retrieved_2nd_on': 1750769785},[],NaN,NaN,False,NaN,AutoModerator,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,1,[],NaN,NaN
80,{'retrieved_2nd_on': 1750769897},[],NaN,NaN,False,NaN,Odd-Principle8147,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,4,[],NaN,NaN
84,{'retrieved_2nd_on': 1750770024},[],NaN,NaN,False,NaN,loufalnicek,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,9,[],NaN,NaN
85,{'retrieved_2nd_on': 1750770042},[],NaN,NaN,False,NaN,XXSeaBeeXX,transparent,Liberal,[],...,r/AskALiberal,public,NaN,0,[],NaN,15,[],NaN,NaN
87,{'retrieved_2nd_on': 1750770082},[],NaN,NaN,False,NaN,LemonySnacker,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,-9,[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6653,{'retrieved_2nd_on': 1751015078},[],NaN,NaN,False,NaN,Wintores,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,1,[],NaN,NaN
6687,{'retrieved_2nd_on': 1751016550},[],NaN,NaN,False,NaN,PeterRum,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,1,[],NaN,NaN
6690,{'retrieved_2nd_on': 1751017005},[],NaN,NaN,False,NaN,hoyden2,transparent,Liberal,[],...,r/AskALiberal,public,NaN,0,[],NaN,1,[],NaN,NaN
6811,"{'is_edited': True, 'retrieved_2nd_on': 175102...",[],NaN,NaN,False,NaN,FrontOfficeNuts,transparent,Liberal,[],...,r/AskALiberal,public,NaN,0,[],NaN,1,[],NaN,NaN
6826,{'retrieved_2nd_on': 1751024105},[],NaN,NaN,False,NaN,Helltenant,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,0,[],NaN,NaN

In [352]:
# print post name and their comments
for i in range (10):
    post_name = posts.iloc[i]['name']
    post_title = posts.iloc[i]['title']
    post_comments = comments[comments['link_id'] == post_name]
    print(f"Post: {post_title}")
    print("Comments:")
    comment_list = []
    for comment in post_comments['body']:
        comment_list.append(comment)
    print(comment_list)
    print("\n")

Post: Coming to a balanced take on immigration
Comments:
[]


Post: Why is that when Democrats lose, they must move to the center rather than the left? How is becoming diet fascists the way to defeat fascists?
Comments:

In [353]:
# group comments by post

# merge posts and comments on post name and link_id
merged = pd.merge(
    posts, 
    comments, 
    left_on='name', 
    right_on='link_id', 
    how='inner', 
    suffixes=('_post', '_comment')  # This renames _x and _y
)

merged

,_meta_post,all_awardings_post,allow_live_comments,approved_at_utc_post,approved_by_post,archived_post,author_post,author_flair_background_color_post,author_flair_css_class_post,author_flair_richtext_post,...,subreddit_name_prefixed_comment,subreddit_type_comment,top_awarded_type_comment,total_awards_received_comment,treatment_tags_comment,unrepliable_reason,ups_comment,user_reports_comment,author_cakeday,editable
0,{'retrieved_2nd_on': 1750769783},[],False,NaN,NaN,False,LemonySnacker,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,1,[],NaN,NaN
1,{'retrieved_2nd_on': 1750769783},[],False,NaN,NaN,False,LemonySnacker,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,4,[],NaN,NaN
2,{'retrieved_2nd_on': 1750769783},[],False,NaN,NaN,False,LemonySnacker,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,9,[],NaN,NaN
3,{'retrieved_2nd_on': 1750769783},[],False,NaN,NaN,False,LemonySnacker,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,15,[],NaN,NaN
4,{'retrieved_2nd_on': 1750769783},[],False,NaN,NaN,False,LemonySnacker,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,-9,[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19341,"{'edited_title': '[ Removed by moderator ]', '...",[],False,NaN,NaN,False,strugglingerdevelop,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,3,[],NaN,NaN
19342,"{'edited_title': '[ Removed by moderator ]', '...",[],False,NaN,NaN,False,strugglingerdevelop,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,2,[],NaN,NaN
19343,"{'edited_title': '[ Removed by moderator ]', '...",[],False,NaN,NaN,False,strugglingerdevelop,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,-5,[],NaN,NaN
19344,"{'edited_title': '[ Removed by moderator ]', '...",[],False,NaN,NaN,False,strugglingerdevelop,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,3,[],NaN,NaN
19345,"{'edited_title': '[ Removed by moderator ]', '...",[],False,NaN,NaN,False,strugglingerdevelop,NaN,NaN,[],...,r/AskALiberal,public,NaN,0,[],NaN,10,[],NaN,NaN

overfitting on posts > finding posts that are irrelevant

In [354]:
import re

# have an LLM generate keywords? This is much faster

candidates = [
    "Zohran", "Mamdani", "Andrew Cuomo", "Cuomo", "Curtis Sliwa", "Sliwa", 
    "Eric Adams", "Brad Lander", "Adrienne Adams", "Scott Stringer", 
    "Zellnor Myrie", "Jessica Ramos", "Jim Walden"
]

events_and_parties = [
    "Ranked Choice", "RCV", "Fight and Deliver", "WFP", "Working Families Party",
    "Mayoral Election", "Democratic Primary", "June 24", "November 4"
]

policies = [
    "Rent freeze", "fare-free buses", "free childcare", "public supermarkets",
    "congestion pricing", "Department of Community Safety"
]

# Combine and escape (to handle special characters)
all_terms = candidates + events_and_parties + policies
pattern_string = r"(?i)\b(" + "|".join(map(re.escape, all_terms)) + r")\b"

# Create the compiled regex
election_regex = re.compile(pattern_string)


merged['is_election_related'] = (
    merged['title'].str.contains(election_regex, na=False) | 
    merged['selftext'].str.contains(election_regex, na=False)
)

# Filter for the relevant rows
df_2025_filtered = merged[merged['is_election_related']].copy()

/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_79014/970100265.py:30: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merged['title'].str.contains(election_regex, na=False) |
/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_79014/970100265.py:31: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merged['selftext'].str.contains(election_regex, na=False)
/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_79014/970100265.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged['is_election_related'] = (

In [355]:
df_2025_filtered['title']

958      How would you rank the Democratic Candidates i...
959      How would you rank the Democratic Candidates i...
960      How would you rank the Democratic Candidates i...
961      How would you rank the Democratic Candidates i...
962      How would you rank the Democratic Candidates i...
                               ...
13418    Should the Democrats be running left-wing popu...
13419    Should the Democrats be running left-wing popu...
13420    Should the Democrats be running left-wing popu...
13421    Should the Democrats be running left-wing popu...
13422    Should the Democrats be running left-wing popu...
Name: title, Length: 1434, dtype: str

In [356]:
filtered = list(df_2025_filtered['title'].unique())
filtered

["How would you rank the Democratic Candidates in New York City's Mayoral Primary? Why?",
 "What's your ideal way of maximizing democratic representation?",
 'How would Rank Choice Voting work for the Presidential Election?',
 'Which camp are you in? Who "should" win the NYC mayoral race?',
 'Does the pushback against Mamdani prove there is only one party?',
 "MEGATHREAD NYC Mayor's Race - Mamdani Projected to Win. Cuomo Concedes",
 'Is "vote blue no matter who" still a thing?',
 'What do you expect from a Mamdani term?',
 "What does the endorsement Cuomo, a sexual predator, by establishment Dems say about how much they truly care about Me Too, feminism and/or a woman's safety?",
 'Why should or shouldn’t New Yorkers vote for Mamdani?',
 'Who should be mayor of NYC? Cuomo or Mamdani?',
 'Do you agree with this statement: "if you were to confect the next winning national candidate in a lab, they\'d be an anti-AI socialist"?',
 'What are your thoughts on “Third Worldism” and how much influence does this ideology have in the modern left?',
 'Many of the most progressive representatives and candidates on the left are Muslim. How does that reconcile with the commonly held belief that Islam is incompatible with western democracy?',
 'Can we have a mature discussion about Zohran Mamdani?',
 "Should the Democrats be running left-wing populists like Ireland's new socialist president, Catherine Connolly?"]

In [357]:
len(list(df_2025_filtered['title'].unique()))

16

In [358]:
df_2025_filtered

,_meta_post,all_awardings_post,allow_live_comments,approved_at_utc_post,approved_by_post,archived_post,author_post,author_flair_background_color_post,author_flair_css_class_post,author_flair_richtext_post,...,subreddit_type_comment,top_awarded_type_comment,total_awards_received_comment,treatment_tags_comment,unrepliable_reason,ups_comment,user_reports_comment,author_cakeday,editable,is_election_related
958,"{'is_edited': True, 'retrieved_2nd_on': 175082...",[],False,NaN,NaN,False,othelloinc,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
959,"{'is_edited': True, 'retrieved_2nd_on': 175082...",[],False,NaN,NaN,False,othelloinc,NaN,NaN,[],...,public,NaN,0,[],NaN,7,[],NaN,NaN,True
960,"{'is_edited': True, 'retrieved_2nd_on': 175082...",[],False,NaN,NaN,False,othelloinc,NaN,NaN,[],...,public,NaN,0,[],NaN,17,[],NaN,NaN,True
961,"{'is_edited': True, 'retrieved_2nd_on': 175082...",[],False,NaN,NaN,False,othelloinc,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
962,"{'is_edited': True, 'retrieved_2nd_on': 175082...",[],False,NaN,NaN,False,othelloinc,NaN,NaN,[],...,public,NaN,0,[],NaN,3,[],NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13418,"{'is_edited': True, 'removal_type': 'moderator...",[],False,NaN,NaN,False,Droselmeyer,NaN,NaN,[],...,public,NaN,0,[],NaN,2,[],NaN,NaN,True
13419,"{'is_edited': True, 'removal_type': 'moderator...",[],False,NaN,NaN,False,Droselmeyer,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
13420,"{'is_edited': True, 'removal_type': 'moderator...",[],False,NaN,NaN,False,Droselmeyer,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True
13421,"{'is_edited': True, 'removal_type': 'moderator...",[],False,NaN,NaN,False,Droselmeyer,NaN,NaN,[],...,public,NaN,0,[],NaN,2,[],NaN,NaN,True
13422,"{'is_edited': True, 'removal_type': 'moderator...",[],False,NaN,NaN,False,Droselmeyer,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,True

In [359]:
print(list(merged.columns))

['_meta_post', 'all_awardings_post', 'allow_live_comments', 'approved_at_utc_post', 'approved_by_post', 'archived_post', 'author_post', 'author_flair_background_color_post', 'author_flair_css_class_post', 'author_flair_richtext_post', 'author_flair_template_id_post', 'author_flair_text_post', 'author_flair_text_color_post', 'author_flair_type_post', 'author_fullname_post', 'author_is_blocked_post', 'author_patreon_flair_post', 'author_premium_post', 'awarders_post', 'banned_at_utc_post', 'banned_by_post', 'can_gild_post', 'can_mod_post_post', 'category', 'clicked', 'content_categories', 'contest_mode', 'created_post', 'created_utc_post', 'discussion_type', 'distinguished_post', 'domain', 'downs_post', 'edited_post', 'gilded_post', 'gildings_post', 'hidden', 'hide_score', 'id_post', 'is_created_from_ads_ui', 'is_crosspostable', 'is_meta', 'is_original_content', 'is_reddit_media_domain', 'is_robot_indexable', 'is_self', 'is_video', 'likes_post', 'link_flair_background_color', 'link_flair_css_class', 'link_flair_richtext', 'link_flair_text', 'link_flair_text_color', 'link_flair_type', 'locked_post', 'media', 'media_embed', 'media_only', 'mod_note_post', 'mod_reason_by_post', 'mod_reason_title_post', 'mod_reports_post', 'name_post', 'no_follow_post', 'num_comments', 'num_crossposts', 'num_reports_post', 'over_18', 'permalink_post', 'pinned', 'pwls', 'quarantine', 'removal_reason_post', 'removed_by', 'removed_by_category', 'report_reasons_post', 'retrieved_on_post', 'saved_post', 'score_post', 'secure_media', 'secure_media_embed', 'selftext', 'send_replies_post', 'spoiler', 'stickied_post', 'subreddit_post', 'subreddit_id_post', 'subreddit_name_prefixed_post', 'subreddit_subscribers', 'subreddit_type_post', 'suggested_sort', 'thumbnail', 'thumbnail_height', 'thumbnail_width', 'title', 'top_awarded_type_post', 'total_awards_received_post', 'treatment_tags_post', 'ups_post', 'upvote_ratio', 'url', 'user_reports_post', 'view_count', 'visited', 'wls', 'preview', 'post_hint', 'poll_data', '_meta_comment', 'all_awardings_comment', 'approved_at_utc_comment', 'approved_by_comment', 'archived_comment', 'associated_award', 'author_comment', 'author_flair_background_color_comment', 'author_flair_css_class_comment', 'author_flair_richtext_comment', 'author_flair_template_id_comment', 'author_flair_text_comment', 'author_flair_text_color_comment', 'author_flair_type_comment', 'author_fullname_comment', 'author_is_blocked_comment', 'author_patreon_flair_comment', 'author_premium_comment', 'awarders_comment', 'banned_at_utc_comment', 'banned_by_comment', 'body', 'can_gild_comment', 'can_mod_post_comment', 'collapsed', 'collapsed_because_crowd_control', 'collapsed_reason', 'collapsed_reason_code', 'comment_type', 'controversiality', 'created_comment', 'created_utc_comment', 'distinguished_comment', 'downs_comment', 'edited_comment', 'gilded_comment', 'gildings_comment', 'id_comment', 'is_submitter', 'likes_comment', 'link_id', 'locked_comment', 'mod_note_comment', 'mod_reason_by_comment', 'mod_reason_title_comment', 'mod_reports_comment', 'name_comment', 'no_follow_comment', 'num_reports_comment', 'parent_id', 'permalink_comment', 'removal_reason_comment', 'replies', 'report_reasons_comment', 'retrieved_on_comment', 'saved_comment', 'score_comment', 'score_hidden', 'send_replies_comment', 'stickied_comment', 'subreddit_comment', 'subreddit_id_comment', 'subreddit_name_prefixed_comment', 'subreddit_type_comment', 'top_awarded_type_comment', 'total_awards_received_comment', 'treatment_tags_comment', 'unrepliable_reason', 'ups_comment', 'user_reports_comment', 'author_cakeday', 'editable', 'is_election_related']

In [360]:
merged['created_utc_post'] = pd.to_datetime(merged['created_utc_post'], unit='s')
merged['created_utc_comment'] = pd.to_datetime(merged['created_utc_comment'], unit='s')

In [361]:
filtered = merged[['title', 'body', 'ups_post', 'ups_comment', 'downs_post', 'downs_comment', 'created_utc_post', 'created_utc_comment']]
filtered = filtered[filtered['body'] != '[removed]']
filtered['body'] = filtered['body'].str.replace(r'\s+', ' ', regex=True).str.strip()
filtered['body'] = filtered['body'].str.lower()
filtered['title'] = filtered['title'].str.lower()
filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment
0,"why is that when democrats lose, they must mov...",the following is a copy of the original post t...,27,1,0,0,2025-06-23 00:56:17,2025-06-23 00:56:18
1,"why is that when democrats lose, they must mov...",because they are looking at what won the elect...,27,4,0,0,2025-06-23 00:56:17,2025-06-23 00:58:07
2,"why is that when democrats lose, they must mov...",because you need to win votes.,27,9,0,0,2025-06-23 00:56:17,2025-06-23 01:00:14
3,"why is that when democrats lose, they must mov...",because perhaps lucy won’t pull the football t...,27,15,0,0,2025-06-23 00:56:17,2025-06-23 01:00:31
4,"why is that when democrats lose, they must mov...",90 million voters stayed home. start getting t...,27,-9,0,0,2025-06-23 00:56:17,2025-06-23 01:01:14
...,...,...,...,...,...,...,...,...
19341,do you believe there was an epstein list cover...,"they're not the same thing. support of israel,...",0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:50:27
19342,do you believe there was an epstein list cover...,i meant judaism to refer to jewishness in gene...,0,2,0,0,2025-11-06 22:07:09,2025-11-06 23:51:50
19343,do you believe there was an epstein list cover...,"> in addition, trump's former labor secretary,...",0,-5,0,0,2025-11-06 22:07:09,2025-11-06 23:53:24
19344,do you believe there was an epstein list cover...,going back to my example... if you think “rape...,0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02
19345,do you believe there was an epstein list cover...,"that was also *explicitly* labeled ""phase 1"". ...",0,10,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02

In [362]:
filtered 

detector = LanguageDetectorBuilder.from_languages(Language.ENGLISH).build()

def check_english(text):
    if type(text) != str:
        return False
    result = detector.detect_language_of(text)
    return result == Language.ENGLISH

filtered['is_english'] = filtered['body'].apply(check_english)
filtered = filtered[filtered['is_english'] == True]

In [363]:
filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment,is_english
0,"why is that when democrats lose, they must mov...",the following is a copy of the original post t...,27,1,0,0,2025-06-23 00:56:17,2025-06-23 00:56:18,True
1,"why is that when democrats lose, they must mov...",because they are looking at what won the elect...,27,4,0,0,2025-06-23 00:56:17,2025-06-23 00:58:07,True
2,"why is that when democrats lose, they must mov...",because you need to win votes.,27,9,0,0,2025-06-23 00:56:17,2025-06-23 01:00:14,True
3,"why is that when democrats lose, they must mov...",because perhaps lucy won’t pull the football t...,27,15,0,0,2025-06-23 00:56:17,2025-06-23 01:00:31,True
4,"why is that when democrats lose, they must mov...",90 million voters stayed home. start getting t...,27,-9,0,0,2025-06-23 00:56:17,2025-06-23 01:01:14,True
...,...,...,...,...,...,...,...,...,...
19341,do you believe there was an epstein list cover...,"they're not the same thing. support of israel,...",0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:50:27,True
19342,do you believe there was an epstein list cover...,i meant judaism to refer to jewishness in gene...,0,2,0,0,2025-11-06 22:07:09,2025-11-06 23:51:50,True
19343,do you believe there was an epstein list cover...,"> in addition, trump's former labor secretary,...",0,-5,0,0,2025-11-06 22:07:09,2025-11-06 23:53:24,True
19344,do you believe there was an epstein list cover...,going back to my example... if you think “rape...,0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02,True
19345,do you believe there was an epstein list cover...,"that was also *explicitly* labeled ""phase 1"". ...",0,10,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02,True

In [364]:
filtered['comment_length'] = filtered['body'].apply(len)
filtered['title_length'] = filtered['title'].apply(len)

filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment,is_english,comment_length,title_length
0,"why is that when democrats lose, they must mov...",the following is a copy of the original post t...,27,1,0,0,2025-06-23 00:56:17,2025-06-23 00:56:18,True,697,141
1,"why is that when democrats lose, they must mov...",because they are looking at what won the elect...,27,4,0,0,2025-06-23 00:56:17,2025-06-23 00:58:07,True,50,141
2,"why is that when democrats lose, they must mov...",because you need to win votes.,27,9,0,0,2025-06-23 00:56:17,2025-06-23 01:00:14,True,30,141
3,"why is that when democrats lose, they must mov...",because perhaps lucy won’t pull the football t...,27,15,0,0,2025-06-23 00:56:17,2025-06-23 01:00:31,True,55,141
4,"why is that when democrats lose, they must mov...",90 million voters stayed home. start getting t...,27,-9,0,0,2025-06-23 00:56:17,2025-06-23 01:01:14,True,94,141
...,...,...,...,...,...,...,...,...,...,...,...
19341,do you believe there was an epstein list cover...,"they're not the same thing. support of israel,...",0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:50:27,True,216,50
19342,do you believe there was an epstein list cover...,i meant judaism to refer to jewishness in gene...,0,2,0,0,2025-11-06 22:07:09,2025-11-06 23:51:50,True,327,50
19343,do you believe there was an epstein list cover...,"> in addition, trump's former labor secretary,...",0,-5,0,0,2025-11-06 22:07:09,2025-11-06 23:53:24,True,771,50
19344,do you believe there was an epstein list cover...,going back to my example... if you think “rape...,0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02,True,847,50
19345,do you believe there was an epstein list cover...,"that was also *explicitly* labeled ""phase 1"". ...",0,10,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02,True,86,50

In [365]:
filtered['comment_length'].mean()

np.float64(336.21308297330233)

In [366]:
filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment,is_english,comment_length,title_length
0,"why is that when democrats lose, they must mov...",the following is a copy of the original post t...,27,1,0,0,2025-06-23 00:56:17,2025-06-23 00:56:18,True,697,141
1,"why is that when democrats lose, they must mov...",because they are looking at what won the elect...,27,4,0,0,2025-06-23 00:56:17,2025-06-23 00:58:07,True,50,141
2,"why is that when democrats lose, they must mov...",because you need to win votes.,27,9,0,0,2025-06-23 00:56:17,2025-06-23 01:00:14,True,30,141
3,"why is that when democrats lose, they must mov...",because perhaps lucy won’t pull the football t...,27,15,0,0,2025-06-23 00:56:17,2025-06-23 01:00:31,True,55,141
4,"why is that when democrats lose, they must mov...",90 million voters stayed home. start getting t...,27,-9,0,0,2025-06-23 00:56:17,2025-06-23 01:01:14,True,94,141
...,...,...,...,...,...,...,...,...,...,...,...
19341,do you believe there was an epstein list cover...,"they're not the same thing. support of israel,...",0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:50:27,True,216,50
19342,do you believe there was an epstein list cover...,i meant judaism to refer to jewishness in gene...,0,2,0,0,2025-11-06 22:07:09,2025-11-06 23:51:50,True,327,50
19343,do you believe there was an epstein list cover...,"> in addition, trump's former labor secretary,...",0,-5,0,0,2025-11-06 22:07:09,2025-11-06 23:53:24,True,771,50
19344,do you believe there was an epstein list cover...,going back to my example... if you think “rape...,0,3,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02,True,847,50
19345,do you believe there was an epstein list cover...,"that was also *explicitly* labeled ""phase 1"". ...",0,10,0,0,2025-11-06 22:07:09,2025-11-06 23:54:02,True,86,50

In [367]:
filtered.to_csv('filtered_reddit_data.csv', index=False)