In [1]:
%pip install numpy

Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (2.4.2)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install lingua-language-detector

Requirement already satisfied: lingua-language-detector in /opt/homebrew/lib/python3.11/site-packages (2.1.1)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
from lingua import Language, LanguageDetectorBuilder

In [4]:
posts = pd.read_json('../r_republican_posts.jsonl', lines=True)
posts

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,visited,wls,gallery_data,is_gallery,media_metadata,author_cakeday,link_flair_template_id,crosspost_parent,crosspost_parent_list,poll_data
0,{'retrieved_2nd_on': 1730548988},[],False,NaN,NaN,False,hugead83883,NaN,NaN,[],...,False,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'removal_type': 'reddit', 'retrieved_2nd_on':...",[],False,NaN,NaN,False,TruthBomb4547,NaN,NaN,[],...,False,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'retrieved_2nd_on': 1730550644},[],False,NaN,NaN,False,ValerioMuredda_,NaN,NaN,[],...,False,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'retrieved_2nd_on': 1730552535},[],False,NaN,NaN,False,PaleWendigo,NaN,NaN,[],...,False,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'retrieved_2nd_on': 1730555992},[],False,NaN,NaN,False,TaskNo4176,NaN,NaN,[],...,False,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17285,{'retrieved_2nd_on': 1762585369},[],False,NaN,NaN,False,thatoneguywhogooned,NaN,NaN,[],...,False,NaN,NaN,NaN,NaN,NaN,f543f008-189a-11e2-acdc-12313b088941,NaN,NaN,NaN
17286,{'retrieved_2nd_on': 1762586614},[],False,NaN,NaN,False,concernedWaCon,NaN,NaN,[],...,False,NaN,NaN,NaN,NaN,NaN,f9ef1a38-189a-11e2-bda2-12313d14a568,NaN,NaN,NaN
17287,{'retrieved_2nd_on': 1762586859},[],False,NaN,NaN,False,FewTechnology1258,NaN,NaN,[],...,False,NaN,NaN,NaN,NaN,NaN,f543f008-189a-11e2-acdc-12313b088941,NaN,NaN,NaN
17288,{'retrieved_2nd_on': 1762587470},[],False,NaN,NaN,False,origutamos,#dadada,NaN,[],...,False,NaN,NaN,NaN,NaN,NaN,18cc4210-c418-11ef-8b00-9a857c176dc4,NaN,NaN,NaN
17289,{'retrieved_2nd_on': 1762590778},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,False,NaN,NaN,NaN,NaN,NaN,f9ef1a38-189a-11e2-bda2-12313d14a568,NaN,NaN,NaN

In [5]:
posts["title"]

0        Putin Releases 4,000 Page Report Exposing How ...
1        Bill Clinton appears to admit the Trump econom...
2          DOES MY VOTE COUNT IF I VOTE RED IN CALIFORNIA?
3        There have been far fewer mail in ballots requ...
4        WATCH: OSCAR® NOMINATED | RED, WHITE AND BLUE ...
                               ...
17285    first irl stream snipe did it before it even s...
17286    Wa Initiative Measure No. IL26-638 Don't be mi...
17287                               Voting bass on vibes 😍
17288    Another day in J.B. Pritzker's paradise - Chic...
17289    So It BEGINS: Check Out List of Anti-Israel DE...
Name: title, Length: 17290, dtype: str

In [6]:
comments = pd.read_json('../r_republican_comments.jsonl', lines=True)
comments

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,ups,user_reports,editable,author_cakeday,media_metadata
0,{'retrieved_2nd_on': 1730548827},[],NaN,NaN,False,NaN,smartassboomer,NaN,NaN,[],...,public,NaN,0,[],NaN,-1,[],NaN,NaN,NaN
1,{'retrieved_2nd_on': 1730548888},[],NaN,NaN,False,NaN,DrakeVampiel,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
2,{'retrieved_2nd_on': 1730548933},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
3,{'retrieved_2nd_on': 1730548988},[],NaN,NaN,False,NaN,AutoModerator,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
4,{'retrieved_2nd_on': 1730549085},[],NaN,NaN,False,NaN,zachomara,NaN,NaN,[],...,public,NaN,0,[],NaN,5,[],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172074,{'retrieved_2nd_on': 1762600761},[],NaN,NaN,False,NaN,Squanchings,NaN,NaN,[],...,public,NaN,0,[],NaN,-1,[],NaN,NaN,NaN
172075,{'retrieved_2nd_on': 1762601643},[],NaN,NaN,False,NaN,TurnThatTVOFF,NaN,NaN,[],...,public,NaN,0,[],NaN,3,[],NaN,NaN,NaN
172076,{'retrieved_2nd_on': 1762601668},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
172077,{'retrieved_2nd_on': 1762602945},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
172078,{'retrieved_2nd_on': 1762603197},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN

In [7]:
posts.iloc[:1]['name']

0    t3_1ggsrp8
Name: name, dtype: str

In [8]:
comments.iloc[:1]['link_id']

0    t3_1gg695z
Name: link_id, dtype: str

In [9]:
# for the first 10 posts, find all comments
first_10_posts = posts.iloc[:10]['name']
first_10_comments = comments[comments['link_id'].isin(first_10_posts)]
first_10_comments

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,ups,user_reports,editable,author_cakeday,media_metadata
3,{'retrieved_2nd_on': 1730548988},[],NaN,NaN,False,NaN,AutoModerator,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
7,{'retrieved_2nd_on': 1730549324},[],NaN,NaN,False,NaN,AutoModerator,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
76,{'retrieved_2nd_on': 1730555992},[],NaN,NaN,False,NaN,AutoModerator,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
515,{'retrieved_2nd_on': 1730608320},[],NaN,NaN,False,NaN,Tori-Chambers,NaN,NaN,[],...,public,NaN,0,[],NaN,2,[],NaN,NaN,NaN
710,{'retrieved_2nd_on': 1730623109},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
895,{'retrieved_2nd_on': 1730635029},[],NaN,NaN,False,NaN,SpringShepHerd,NaN,NaN,[],...,public,NaN,0,[],NaN,3,[],NaN,NaN,NaN
899,{'retrieved_2nd_on': 1730635221},[],NaN,NaN,False,NaN,Equivalent-Ad8645,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
901,{'retrieved_2nd_on': 1730635263},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
906,{'retrieved_2nd_on': 1730635775},[],NaN,NaN,False,NaN,jjk5305,NaN,NaN,[],...,public,NaN,0,[],NaN,4,[],NaN,NaN,NaN
920,{'retrieved_2nd_on': 1730636391},[],NaN,NaN,False,NaN,Impossible-Pin2457,NaN,NaN,[],...,public,NaN,0,[],NaN,2,[],NaN,NaN,NaN
922,{'retrieved_2nd_on': 1730636445},[],NaN,NaN,False,NaN,SpringShepHerd,NaN,NaN,[],...,public,NaN,0,[],NaN,3,[],NaN,NaN,NaN
944,{'retrieved_2nd_on': 1730637562},[],NaN,NaN,False,NaN,laurvo,NaN,NaN,[],...,public,NaN,0,[],NaN,3,[],NaN,NaN,NaN
984,{'retrieved_2nd_on': 1730640005},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
1521,"{'is_edited': True, 'removal_type': 'removed',...",[],NaN,NaN,False,NaN,Junior_Adeptness_792,,NaN,[],...,public,NaN,0,[],NaN,5,[],NaN,NaN,NaN
1988,"{'is_edited': True, 'removal_type': 'removed',...",[],NaN,NaN,False,NaN,No_Caterpillar6536,,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
2144,"{'is_edited': True, 'removal_type': 'removed',...",[],NaN,NaN,False,NaN,TheThreesFifthComp,,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
2254,{'retrieved_2nd_on': 1730771292},[],NaN,NaN,False,NaN,RedBaronsBrother,NaN,NaN,[],...,public,NaN,0,[],NaN,2,[],NaN,NaN,NaN
2705,{'retrieved_2nd_on': 1730805007},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
2877,{'retrieved_2nd_on': 1730815901},[],NaN,NaN,False,NaN,[deleted],,NaN,NaN,...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN

In [10]:
# print post name and their comments
for i in range (10):
    post_name = posts.iloc[i]['name']
    post_title = posts.iloc[i]['title']
    post_comments = comments[comments['link_id'] == post_name]
    print(f"Post: {post_title}")
    print("Comments:")
    comment_list = []
    for comment in post_comments['body']:
        comment_list.append(comment)
    print(comment_list)
    print("\n")

Post: Putin Releases 4,000 Page Report Exposing How Elites Have Rigged 2024 US Election
Comments:
["/r/Republican is a partisan subreddit.  This is a place for Republicans to discuss issues with other Republicans.\nTo those visiting this thread, we ask that unless you identify as Republican that you refrain from commenting and [leave the vote button alone](https://www.reddit.com/r/MetaRepublican/comments/5t017a/this_sub_is_for_republicans_if_you_do_not/). Non republicans who come to our sub looking for a 'different perspective' [subvert that very perspective with their own views when they vote or comment.](http://i.imgur.com/XqL0wfR.jpg)\n\n*I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/Republican) if you have any questions or concerns.*"]


Post: Bill Clinton appears to admit the Trump economy 'was better' | Fox News Video
Comments:
["/r/Republican is a partisan subreddit.  This is a place for Republicans to discuss issues with other Republicans.\nTo those visiting this thread, we ask that unless you identify as Republican that you refrain from commenting and [leave the vote button alone](https://www.reddit.com/r/MetaRepublican/comments/5t017a/this_sub_is_for_republicans_if_you_do_not/). Non republicans who come to our sub looking for a 'different perspective' [subvert that very perspective with their own views when they vote or comment.](http://i.imgur.com/XqL0wfR.jpg)\n\n*I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/Republican) if you have any questions or concerns.*", "Bill is still upset that Hillary didn't win in 2016, and will do whatever it takes to make anyone else look bad.", 'A lot of things were far better. Look at immigration https://www.dailywire.com/news/biden-admin-authorizes-mass-overtime-to-process-haitian-migrants-before-inauguration-day-agent-says']


Post: DOES MY VOTE COUNT IF I VOTE RED IN CALIFORNIA?
Comments:
[]


Post: There have been far fewer mail in ballots requested in PA by Democrats in 2024 than 2020
Comments:
[]


Post: WATCH: OSCAR® NOMINATED | RED, WHITE AND BLUE | SHORT FILM (FULL)
Comments:
["/r/Republican is a partisan subreddit.  This is a place for Republicans to discuss issues with other Republicans.\nTo those visiting this thread, we ask that unless you identify as Republican that you refrain from commenting and [leave the vote button alone](https://www.reddit.com/r/MetaRepublican/comments/5t017a/this_sub_is_for_republicans_if_you_do_not/). Non republicans who come to our sub looking for a 'different perspective' [subvert that very perspective with their own views when they vote or comment.](http://i.imgur.com/XqL0wfR.jpg)\n\n*I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/Republican) if you have any questions or concerns.*"]


Post: TRUMP 2024!!!!
Comments:
['Put my vote in in Ramsey county. Get out there and vote!', '[removed]', 'My vote was in Colorado. So many damn Harris signs in my town though.\n\nIck....I want this state to flip BAD!', "Yeah I'm planning on moving to I think Iowa or maybe Texas soon."]


Post: Make America Garbage Again 🇺🇸✊🏼
Comments:
['[removed]', 'MAGA women are the hottest women 😬', 'Ain’t that the truth!!!!! 🇺🇸✊🏼🇺🇸✊🏼', '[removed]', 'My favorite part is that they don’t have a penis.', 'is it still funny if they laugh at you', 'Hahahahahahahaha', "Yes.  That's one of the differences between the left and right.  We can laugh at ourselves, and at the absurdity of the left's attacks on us, and even coopt them to make fun of the left.\n\nThe only thing the left finds funny is mean spirited attacks on its opponents.", '[removed]', '[removed]']


Post: IM PROUD TO BE AN AMERICAN.
Comments:
[]


Post: I have a feeling
Comments:
[]


Post: Is it just me, or is the internet being dominated by liberals?
Comments:
[]

In [11]:
# group comments by post

# merge posts and comments on post name and link_id
merged = pd.merge(
    posts, 
    comments, 
    left_on='name', 
    right_on='link_id', 
    how='inner', 
    suffixes=('_post', '_comment')  # This renames _x and _y
)

merged

,_meta_post,all_awardings_post,allow_live_comments,approved_at_utc_post,approved_by_post,archived_post,author_post,author_flair_background_color_post,author_flair_css_class_post,author_flair_richtext_post,...,subreddit_type_comment,top_awarded_type_comment,total_awards_received_comment,treatment_tags_comment,unrepliable_reason,ups_comment,user_reports_comment,editable,author_cakeday_comment,media_metadata_comment
0,{'retrieved_2nd_on': 1730548988},[],False,NaN,NaN,False,hugead83883,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
1,"{'removal_type': 'reddit', 'retrieved_2nd_on':...",[],False,NaN,NaN,False,TruthBomb4547,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
2,"{'removal_type': 'reddit', 'retrieved_2nd_on':...",[],False,NaN,NaN,False,TruthBomb4547,NaN,NaN,[],...,public,NaN,0,[],NaN,2,[],NaN,NaN,NaN
3,"{'removal_type': 'reddit', 'retrieved_2nd_on':...",[],False,NaN,NaN,False,TruthBomb4547,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
4,{'retrieved_2nd_on': 1730555992},[],False,NaN,NaN,False,TaskNo4176,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171357,{'retrieved_2nd_on': 1762568991},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,public,NaN,0,[],NaN,5,[],NaN,NaN,NaN
171358,{'retrieved_2nd_on': 1762587470},[],False,NaN,NaN,False,origutamos,#dadada,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN
171359,{'retrieved_2nd_on': 1762590778},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,public,NaN,0,[],NaN,2,[],NaN,NaN,NaN
171360,{'retrieved_2nd_on': 1762590778},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,public,NaN,0,[],NaN,5,[],NaN,NaN,NaN
171361,{'retrieved_2nd_on': 1762590778},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,public,NaN,0,[],NaN,1,[],NaN,NaN,NaN

overfitting on posts > finding posts that are irrelevant

In [12]:
import re

# have an LLM generate keywords? This is much faster

candidates = [
    "Zohran", "Mamdani", "Andrew Cuomo", "Cuomo", "Curtis Sliwa", "Sliwa", 
    "Eric Adams", "Brad Lander", "Adrienne Adams", "Scott Stringer", 
    "Zellnor Myrie", "Jessica Ramos", "Jim Walden"
]

events_and_parties = [
    "Ranked Choice", "RCV", "Fight and Deliver", "WFP", "Working Families Party",
    "Mayoral Election", "Democratic Primary", "June 24", "November 4"
]

policies = [
    "Rent freeze", "fare-free buses", "free childcare", "public supermarkets",
    "congestion pricing", "Department of Community Safety"
]

# Combine and escape (to handle special characters)
all_terms = candidates + events_and_parties + policies
pattern_string = r"(?i)\b(" + "|".join(map(re.escape, all_terms)) + r")\b"

# Create the compiled regex
election_regex = re.compile(pattern_string)


merged['is_election_related'] = (
    merged['title'].str.contains(election_regex, na=False) | 
    merged['selftext'].str.contains(election_regex, na=False)
)

# Filter for the relevant rows
df_2025_filtered = merged[merged['is_election_related']].copy()

/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_49660/970100265.py:30: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merged['title'].str.contains(election_regex, na=False) |
/var/folders/3t/glkqspd122g2jfyt703d1dmc0000gn/T/ipykernel_49660/970100265.py:31: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merged['selftext'].str.contains(election_regex, na=False)

In [13]:
df_2025_filtered['title']

11578                   Question about Ranked choice voting
29860     Pennsylvania native, former SEC Chair tapped b...
39099     Seismic Shift? White Republican Upsets Black D...
39100     Seismic Shift? White Republican Upsets Black D...
39101     Seismic Shift? White Republican Upsets Black D...
                                ...
171334    Group of Mamdani Voters Try to Explain Why The...
171335    Group of Mamdani Voters Try to Explain Why The...
171359    So It BEGINS: Check Out List of Anti-Israel DE...
171360    So It BEGINS: Check Out List of Anti-Israel DE...
171361    So It BEGINS: Check Out List of Anti-Israel DE...
Name: title, Length: 652, dtype: str

In [14]:
filtered = list(df_2025_filtered['title'].unique())
filtered

['Question about Ranked choice voting',
 'Pennsylvania native, former SEC Chair tapped by Trump p to prosecute P. Diddy, NYC Mayor Eric Adams',
 'Seismic Shift? White Republican Upsets Black Democrat Incumbent in Baton Rouge Mayoral Election',
 'Eric Adams announces more shelter closures in New York',
 'Trump border czar Tom Homan praises Eric Adams for support for deportation plan',
 'Eric Adams Tells Tucker Carlson How Biden, Staff Instructed Him To Be A Good Democrat On Immigration',
 'MTA sues to keep congestion pricing in place after Trump DOT’s ‘mystifying’ decision to pull approval',
 '[White House] “CONGESTION PRICING IS DEAD. Manhattan, and all of New York, is SAVED. LONG LIVE THE KING!” —President Donald J. Trump',
 'JUST IN: NYC Mayor Eric Adams Sues Trump, Kristi Noem, and Scott Bessent Over $80.5M in Revoked Migrant Shelter Funding',
 '5 people have been criminally charged in connection with the misuse of absentee ballots during the 2023 Bridgeport, Connecticut Democratic mayoral election. Absentee ballot fraud helped steal an election. Ok, can we now go after dems who did this to Republicans?!',
 "Bill O'Reilly and Geraldo Rivera debate Trump’s new tariffs | CUOMO",
 'Chris Cuomo Criticizes Trump Admin\'s UAP Secrecy, Discusses New "Tic-Tac" Video Showing Advanced Technology - emerges from water, accelerates to supersonic air-speed.',
 'Mamdani Winning: In Retrospect',
 'The Global Rise Of Sharia Law And Mamdani’s ‘Intifada’ Silence',
 'Zohran Mamdani Hires Private Security After Calling to Defund Police',
 'Reminder that Mamdani lied about being black on his college application to take advantage of policies meant to help underprivileged students',
 "Zohran Mamdani is a wolf in sheep's clothing.",
 'Mamdani, AOC and other DSA members should leave party: Dem Rep. Tom Suozzi insists',
 'Mamdani mayoral campaign took in $13,000 in illegal foreign donations, records show',
 'Leave it to the over-educated, underemployed class in NYC to make this guy their leader of choice.',
 "Zohran Mamdani's Sob Story About His Aunt Being the Real Victim of 9/11 Just Fell Apart – The Details Are Insane!",
 'Kathy Hochul oddly drags Buffalo Bills into ‘tax the rich’ chant that overwhelmed her appearance at Zohran Mamdani rally',
 'Which way NYC Republicans?',
 'Nearly a million New Yorkers ready to flee NYC if Mamdani becomes mayor: poll',
 'Zohran Mamdani has been elected as the mayor of New York City. Has NYC fallen to the communists?',
 'Screen at Mamdani Election Night HQ Hacked with Pro-Trump Message That Made Liberals Heads Explode',
 "Mamdani's Reaction When Told Hakeem Jeffries Doesn’t See Him As Dem Party’s Future Tells You That The Dems Are in for a Surprise (Video)",
 'Group of Mamdani Voters Try to Explain Why They Voted for Him – Ignorance So Bad It Hurts Your Brain! (Video)',
 'So It BEGINS: Check Out List of Anti-Israel DEMANDS Dem Socialists of America Just Handed Mamdani – Radical Agenda Exposed! (Pic)']

In [15]:
len(list(df_2025_filtered['title'].unique()))

29

In [16]:
df_2025_filtered

,_meta_post,all_awardings_post,allow_live_comments,approved_at_utc_post,approved_by_post,archived_post,author_post,author_flair_background_color_post,author_flair_css_class_post,author_flair_richtext_post,...,top_awarded_type_comment,total_awards_received_comment,treatment_tags_comment,unrepliable_reason,ups_comment,user_reports_comment,editable,author_cakeday_comment,media_metadata_comment,is_election_related
11578,{'retrieved_2nd_on': 1731052450},[],False,NaN,NaN,False,hairyviking123,NaN,NaN,[],...,NaN,0,[],NaN,1,[],NaN,NaN,NaN,True
29860,{'retrieved_2nd_on': 1732232202},[],False,NaN,NaN,False,hbg100dotcom,NaN,NaN,[],...,NaN,0,[],NaN,1,[],NaN,NaN,NaN,True
39099,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,NaN,NaN,False,M_i_c_K,NaN,NaN,[],...,NaN,0,[],NaN,1,[],NaN,NaN,NaN,True
39100,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,NaN,NaN,False,M_i_c_K,NaN,NaN,[],...,NaN,0,[],NaN,16,[],NaN,NaN,NaN,True
39101,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,NaN,NaN,False,M_i_c_K,NaN,NaN,[],...,NaN,0,[],NaN,15,[],NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171334,{'retrieved_2nd_on': 1762561206},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,NaN,0,[],NaN,-1,[],NaN,NaN,NaN,True
171335,{'retrieved_2nd_on': 1762561206},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,NaN,0,[],NaN,1,[],NaN,NaN,NaN,True
171359,{'retrieved_2nd_on': 1762590778},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,NaN,0,[],NaN,2,[],NaN,NaN,NaN,True
171360,{'retrieved_2nd_on': 1762590778},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,NaN,0,[],NaN,5,[],NaN,NaN,NaN,True
171361,{'retrieved_2nd_on': 1762590778},[],False,NaN,NaN,False,MackSix,NaN,NaN,[],...,NaN,0,[],NaN,1,[],NaN,NaN,NaN,True

In [17]:
print(list(merged.columns))

['_meta_post', 'all_awardings_post', 'allow_live_comments', 'approved_at_utc_post', 'approved_by_post', 'archived_post', 'author_post', 'author_flair_background_color_post', 'author_flair_css_class_post', 'author_flair_richtext_post', 'author_flair_template_id_post', 'author_flair_text_post', 'author_flair_text_color_post', 'author_flair_type_post', 'author_fullname_post', 'author_is_blocked_post', 'author_patreon_flair_post', 'author_premium_post', 'awarders_post', 'banned_at_utc_post', 'banned_by_post', 'can_gild_post', 'can_mod_post_post', 'category', 'clicked', 'content_categories', 'contest_mode', 'created_post', 'created_utc_post', 'discussion_type', 'distinguished_post', 'domain', 'downs_post', 'edited_post', 'gilded_post', 'gildings_post', 'hidden', 'hide_score', 'id_post', 'is_created_from_ads_ui', 'is_crosspostable', 'is_meta', 'is_original_content', 'is_reddit_media_domain', 'is_robot_indexable', 'is_self', 'is_video', 'likes_post', 'link_flair_background_color', 'link_flair_css_class', 'link_flair_richtext', 'link_flair_text', 'link_flair_text_color', 'link_flair_type', 'locked_post', 'media', 'media_embed', 'media_only', 'mod_note_post', 'mod_reason_by_post', 'mod_reason_title_post', 'mod_reports_post', 'name_post', 'no_follow_post', 'num_comments', 'num_crossposts', 'num_reports_post', 'over_18', 'permalink_post', 'pinned', 'post_hint', 'preview', 'pwls', 'quarantine', 'removal_reason_post', 'removed_by', 'removed_by_category', 'report_reasons_post', 'retrieved_on_post', 'saved_post', 'score_post', 'secure_media', 'secure_media_embed', 'selftext', 'send_replies_post', 'spoiler', 'stickied_post', 'subreddit_post', 'subreddit_id_post', 'subreddit_name_prefixed_post', 'subreddit_subscribers', 'subreddit_type_post', 'suggested_sort', 'thumbnail', 'thumbnail_height', 'thumbnail_width', 'title', 'top_awarded_type_post', 'total_awards_received_post', 'treatment_tags_post', 'ups_post', 'upvote_ratio', 'url', 'url_overridden_by_dest', 'user_reports_post', 'view_count', 'visited', 'wls', 'gallery_data', 'is_gallery', 'media_metadata_post', 'author_cakeday_post', 'link_flair_template_id', 'crosspost_parent', 'crosspost_parent_list', 'poll_data', '_meta_comment', 'all_awardings_comment', 'approved_at_utc_comment', 'approved_by_comment', 'archived_comment', 'associated_award', 'author_comment', 'author_flair_background_color_comment', 'author_flair_css_class_comment', 'author_flair_richtext_comment', 'author_flair_template_id_comment', 'author_flair_text_comment', 'author_flair_text_color_comment', 'author_flair_type_comment', 'author_fullname_comment', 'author_is_blocked_comment', 'author_patreon_flair_comment', 'author_premium_comment', 'awarders_comment', 'banned_at_utc_comment', 'banned_by_comment', 'body', 'can_gild_comment', 'can_mod_post_comment', 'collapsed', 'collapsed_because_crowd_control', 'collapsed_reason', 'collapsed_reason_code', 'comment_type', 'controversiality', 'created_comment', 'created_utc_comment', 'distinguished_comment', 'downs_comment', 'edited_comment', 'gilded_comment', 'gildings_comment', 'id_comment', 'is_submitter', 'likes_comment', 'link_id', 'locked_comment', 'mod_note_comment', 'mod_reason_by_comment', 'mod_reason_title_comment', 'mod_reports_comment', 'name_comment', 'no_follow_comment', 'num_reports_comment', 'parent_id', 'permalink_comment', 'removal_reason_comment', 'replies', 'report_reasons_comment', 'retrieved_on_comment', 'saved_comment', 'score_comment', 'score_hidden', 'send_replies_comment', 'stickied_comment', 'subreddit_comment', 'subreddit_id_comment', 'subreddit_name_prefixed_comment', 'subreddit_type_comment', 'top_awarded_type_comment', 'total_awards_received_comment', 'treatment_tags_comment', 'unrepliable_reason', 'ups_comment', 'user_reports_comment', 'editable', 'author_cakeday_comment', 'media_metadata_comment', 'is_election_related']

In [18]:
merged['created_utc_post'] = pd.to_datetime(merged['created_utc_post'], unit='s')
merged['created_utc_comment'] = pd.to_datetime(merged['created_utc_comment'], unit='s')

In [19]:
filtered = merged[['title', 'body', 'ups_post', 'ups_comment', 'downs_post', 'downs_comment', 'created_utc_post', 'created_utc_comment']]
filtered = filtered[filtered['body'] != '[removed]']
filtered['body'] = filtered['body'].str.replace(r'\s+', ' ', regex=True).str.strip()
filtered['body'] = filtered['body'].str.lower()
filtered['title'] = filtered['title'].str.lower()
filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment
0,"putin releases 4,000 page report exposing how ...",/r/republican is a partisan subreddit. this is...,1,1,0,0,2024-11-01 00:02:43,2024-11-01 00:02:44
1,bill clinton appears to admit the trump econom...,/r/republican is a partisan subreddit. this is...,100,1,0,0,2024-11-01 00:08:32,2024-11-01 00:08:33
2,bill clinton appears to admit the trump econom...,bill is still upset that hillary didn't win in...,100,2,0,0,2024-11-01 00:08:32,2024-11-01 16:31:43
3,bill clinton appears to admit the trump econom...,a lot of things were far better. look at immig...,100,1,0,0,2024-11-01 00:08:32,2024-11-02 00:00:13
4,"watch: oscar® nominated | red, white and blue ...",/r/republican is a partisan subreddit. this is...,1,1,0,0,2024-11-01 01:59:45,2024-11-01 01:59:47
...,...,...,...,...,...,...,...,...
171353,dems attack erika kirk with 'fake tears' video...,so the video of her putting in eye drops befor...,11,-6,0,0,2025-11-06 14:29:02,2025-11-06 21:00:55
171355,dems attack erika kirk with 'fake tears' video...,dry eyes? a very common eye condition.,11,6,0,0,2025-11-06 14:29:02,2025-11-06 22:06:24
171357,dems attack erika kirk with 'fake tears' video...,i mean it could also very clearly be redness d...,11,5,0,0,2025-11-06 14:29:02,2025-11-06 22:29:17
171359,so it begins: check out list of anti-israel de...,the radicals never hid it.. they openly talked...,23,2,0,0,2025-11-06 20:32:49,2025-11-06 20:41:17
171360,so it begins: check out list of anti-israel de...,any enemy of israel will one day be our enemy ...,23,5,0,0,2025-11-06 20:32:49,2025-11-06 22:32:12

In [20]:
filtered 

detector = LanguageDetectorBuilder.from_languages(Language.ENGLISH).build()

def check_english(text):
    result = detector.detect_language_of(text)
    return result == Language.ENGLISH

filtered['is_english'] = filtered['body'].apply(check_english)
filtered = filtered[filtered['is_english'] == True]

In [21]:
filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment,is_english
0,"putin releases 4,000 page report exposing how ...",/r/republican is a partisan subreddit. this is...,1,1,0,0,2024-11-01 00:02:43,2024-11-01 00:02:44,True
1,bill clinton appears to admit the trump econom...,/r/republican is a partisan subreddit. this is...,100,1,0,0,2024-11-01 00:08:32,2024-11-01 00:08:33,True
2,bill clinton appears to admit the trump econom...,bill is still upset that hillary didn't win in...,100,2,0,0,2024-11-01 00:08:32,2024-11-01 16:31:43,True
3,bill clinton appears to admit the trump econom...,a lot of things were far better. look at immig...,100,1,0,0,2024-11-01 00:08:32,2024-11-02 00:00:13,True
4,"watch: oscar® nominated | red, white and blue ...",/r/republican is a partisan subreddit. this is...,1,1,0,0,2024-11-01 01:59:45,2024-11-01 01:59:47,True
...,...,...,...,...,...,...,...,...,...
171353,dems attack erika kirk with 'fake tears' video...,so the video of her putting in eye drops befor...,11,-6,0,0,2025-11-06 14:29:02,2025-11-06 21:00:55,True
171355,dems attack erika kirk with 'fake tears' video...,dry eyes? a very common eye condition.,11,6,0,0,2025-11-06 14:29:02,2025-11-06 22:06:24,True
171357,dems attack erika kirk with 'fake tears' video...,i mean it could also very clearly be redness d...,11,5,0,0,2025-11-06 14:29:02,2025-11-06 22:29:17,True
171359,so it begins: check out list of anti-israel de...,the radicals never hid it.. they openly talked...,23,2,0,0,2025-11-06 20:32:49,2025-11-06 20:41:17,True
171360,so it begins: check out list of anti-israel de...,any enemy of israel will one day be our enemy ...,23,5,0,0,2025-11-06 20:32:49,2025-11-06 22:32:12,True

In [22]:
filtered['comment_length'] = filtered['body'].apply(len)
filtered['title_length'] = filtered['title'].apply(len)

filtered

,title,body,ups_post,ups_comment,downs_post,downs_comment,created_utc_post,created_utc_comment,is_english,comment_length,title_length
0,"putin releases 4,000 page report exposing how ...",/r/republican is a partisan subreddit. this is...,1,1,0,0,2024-11-01 00:02:43,2024-11-01 00:02:44,True,727,81
1,bill clinton appears to admit the trump econom...,/r/republican is a partisan subreddit. this is...,100,1,0,0,2024-11-01 00:08:32,2024-11-01 00:08:33,True,727,77
2,bill clinton appears to admit the trump econom...,bill is still upset that hillary didn't win in...,100,2,0,0,2024-11-01 00:08:32,2024-11-01 16:31:43,True,112,77
3,bill clinton appears to admit the trump econom...,a lot of things were far better. look at immig...,100,1,0,0,2024-11-01 00:08:32,2024-11-02 00:00:13,True,183,77
4,"watch: oscar® nominated | red, white and blue ...",/r/republican is a partisan subreddit. this is...,1,1,0,0,2024-11-01 01:59:45,2024-11-01 01:59:47,True,727,65
...,...,...,...,...,...,...,...,...,...,...,...
171353,dems attack erika kirk with 'fake tears' video...,so the video of her putting in eye drops befor...,11,-6,0,0,2025-11-06 14:29:02,2025-11-06 21:00:55,True,73,100
171355,dems attack erika kirk with 'fake tears' video...,dry eyes? a very common eye condition.,11,6,0,0,2025-11-06 14:29:02,2025-11-06 22:06:24,True,38,100
171357,dems attack erika kirk with 'fake tears' video...,i mean it could also very clearly be redness d...,11,5,0,0,2025-11-06 14:29:02,2025-11-06 22:29:17,True,119,100
171359,so it begins: check out list of anti-israel de...,the radicals never hid it.. they openly talked...,23,2,0,0,2025-11-06 20:32:49,2025-11-06 20:41:17,True,113,129
171360,so it begins: check out list of anti-israel de...,any enemy of israel will one day be our enemy ...,23,5,0,0,2025-11-06 20:32:49,2025-11-06 22:32:12,True,69,129

In [23]:
filtered['comment_length'].mean()

np.float64(210.00725213064422)

In [24]:
filtered.to_csv('filtered_reddit_data.csv', index=False)